### ISSUE TITLE
dotnet-suggest  has a package type 'DotnetTool' that is not supported by project 

### ISSUE THREAD

**Issue by 7934345** [dotnet/command-line-api#1005]
> @ Installing dotnet-suggest in HelloConsole finished (0.309 sec)
> Install failed (project: HelloConsole, package: dotnet-suggest v1.1.137102)
Package 'dotnet-suggest 1.1.137102' has a package type 'DotnetTool' that is not supported by project '/home/jack/Desktop/C#/ApplicationConsole/HelloConsole/HelloConsole.csproj'.

HelloConsole is A .Net Core 3.1 Project

**Comment by jonsequitur** [comment]
This is intentional. `dotnet-suggest` is a [.NET Core tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools), meaning it's an independent executable that's installed via a NuGet package. It's not a library.

Anyone who has `dotnet-suggest` tool installed will be able to get completions for other tools build using the `System.CommandLine` (library) package.
