### ISSUE TITLE
Option constructor binding only usable with required arguments 

### ISSUE THREAD

**Issue by sebastienros** [dotnet/command-line-api#1037]
When an options class is used with a custom constructor like this:

```c#
public class GreeterOptions
{
  public string Name { get; }

  public MyOptions(string name)
  {
    Name = name;
  }
}

var rootCommand = new RootCommand 
{
  new Option<string>("--name", description: "The name")
};

rootCommand.Handler = CommandHandler.Create<GreeterOptions>(Greet);

public static void Greet(GreeterOptions options)
{
  // do something with options
}

```
If any of these is true:
1- `--name` is not defined on the command line
2- the default parameter value is not defined on the option
3- a default parameter value of `null` is used 

The `Greet` method is called with a null value for the `options` parameter.

I would have expected either of these:
- Call the constructor with a default value (`null` in this case) on `name 
- Display the help stating that `--name` is missing, since it doesn't work without it by design

Otherwise the application has no way to know what is missing. Or these options are by design required, which would also result in displaying the help messages.

Mitigations:
- Specify `IsRequired`  or a non-null default parameter lambda on every option.

**Comment by jonsequitur** [comment]
Adding a few details and explanation of the thinking behind the current design.

> Call the constructor with a default value (null in this case) on `name

The assumption is that the constructor won't allow `null` and will throw. This is the common case for types defined in the BCL, for example. We will pass `null` however to a constructor parameter defined with a default value of `null`.

> Display the help stating that --name is missing, since it doesn't work without it by design

This can be done using `Option.IsRequired` but since we don't configure the parser based on the model binding, you have to configure the parser yourself. An app model layer (such as DragonFruit) can provide better synchronization between these two aspects. 

(DragonFruit could be improved to include this but I don't believe it's implemented today.)
