### ISSUE TITLE
Override property bindings?

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/command-line-api#1056]
Is it possible to override the name of which the option will be bound to as I do not wish to use the default convention.
i.e
`new Option<bool>("--config") { BindingName = "hasConfiguration" }`
```
command.Handler = CommandHandler.Create<bool>(
                (hasConfiguration) => Console.WriteLine(hasConfiguration));
```

**Comment by Kralizek** [comment]
@KieranDevvs you can specify the Name of the option so that it can match the parameter/property you want to bind to.

Here I am taking a very verbose way, but it allows me to bind options to names that are nicer to have as properties.

https://github.com/Kralizek/Hyde/blob/prototype/src/Hyde/Commands/Post/NewPostCommand.cs
