### ISSUE TITLE
GetValueOrDefault() crashes with invalid enum values

### ISSUE THREAD

**Issue by ravenpride** [dotnet/command-line-api#1057]
The issue occurs with System.CommandLine version 2.0.0-beta1.20371.2.

The Method `OptionResult.GetValueOrDefault()` throws an exception, if the the option type is an enum and an invalid value is specified. The following example illustrates that:

```csharp
		enum MyEnum
		{
			Cat,
			Dog
		}

		static void Main(string[] args)
		{
			var rootCommand = new RootCommand();
			var globalOption = new Option<MyEnum>(new[] { "--value" }, () => MyEnum.Dog, "xxx");
			globalOption.AddValidator(option => {
				Console.WriteLine("Validating --value...");
				MyEnum value = option.GetValueOrDefault<MyEnum>();   // <--- CRASHES
				Console.WriteLine("The value is '{0}'.", value);
				return null;
			});
			rootCommand.Handler = CommandHandler.Create((MyEnum value) =>
			{
				Console.WriteLine("Root Command here... The value is '{0}'", value);
			});
			rootCommand.AddGlobalOption(globalOption);

			rootCommand.InvokeAsync(args).Wait();
			Console.ReadKey();
		}
```

If you call the program with `app.exe --value=Fox`, it will throw the following exception (encapsulating AggregateException trimmed away):

```
InvalidOperationException: Cannot parse argument 'Fox' for option '--value' as expected type ConsoleApp2.Program+MyEnum.

   bei System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   bei System.CommandLine.Parsing.OptionResultExtensions.GetValueOrDefault[T](OptionResult optionResult)
   bei ConsoleApp2.Program.<>c.<Main>b__1_1(OptionResult option) in C:\Users\fals\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:Zeile 58.
   bei System.CommandLine.Parsing.ParseResultVisitor.ValidateOptionResult(OptionResult optionResult)
   bei System.CommandLine.Parsing.ParseResultVisitor.Stop(SyntaxNode node)
   bei System.CommandLine.Parsing.SyntaxVisitor.Visit(SyntaxNode node)
   bei System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   bei System.CommandLine.CommandExtensions.GetInvocationPipeline(Command command, String[] args)
   bei System.CommandLine.CommandExtensions.<InvokeAsync>d__2.MoveNext()
```

I think the parser should detect the invalid enum value and abort processing with an error code as it does for unknown options before entering the validator.

**Comment by jonsequitur** [comment]
This is intentional. If the value can't be parsed to the target type, then an exception at this level `option.GetValueOrDefault<MyEnum>()` is appropriate, otherwise how do you signal that the value can't be parsed? And an exception in the validator is considered a developer error, not a user error. The validator is expected to handle this, as in the screen shot example below.

(If you want to handle both validation and custom results in one place, the `Argument<T>` and `Option<T>` constructors that accept a `ParseArgument<T>` delegate are generally more flexible than the validator approach.)

![image](https://user-images.githubusercontent.com/547415/101820820-f8b82a80-3adb-11eb-892a-12a5256125f9.png)

**Comment by ravenpride** [comment]
This works perfectly, thank you!
