### ISSUE TITLE
Bool arguments missing name in help page

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/command-line-api#1157]
Consider this application:

```c#
static int Main(string[] args)
{
    var rootCommand = new RootCommand
    {
        new Argument<bool>("value1", "Some value"),
        new Argument<int>("value2", "Another value"),
    };

    rootCommand.Handler = CommandHandler.Create<bool>(value1 =>
    {
        Console.WriteLine($"The value for 'value1' is: {value1}");
    });

    return rootCommand.Invoke(args);
}
```

When calling this application with the `--help` parameter, we get an output like this:

```
Usage:
  CommandLineReproducer [options] [<value1> <value2>]

Arguments:
              Some value
  <value2>    Another value

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information
```

Notice how in the **Arguments** sections we see `<value2>` but not `<value1>`. It seems it's not printed here because the type parameter is `bool`.

**Comment by adamhewitt627** [comment]
I tracked this down to #500, and more specifically: https://github.com/dotnet/command-line-api/blob/4b43131a66cb675d681f23254a08a7e3d34a7e6f/src/System.CommandLine/Help/HelpBuilder.cs#L529-L533

It looks like that change might be _intended_ for when the `Argument` is on an `Option`, while this issue puts it on the root directly and probably should have the `<value1>` included? Or, should it have `<true|false>`?

**Comment by Pxtl** [comment]
The documentation doesn't seem to discuss positional arguments at all, I only found out about them when exploring the source... are they getting deprecated in favour of a flag on options or something similar?

It took me a long time to figure out they even existed because I'm coming to this from PowerShell where an "argument" is just an "option" with an index so it its name is specified optionally, like in C# with the optional parameters.

**Comment by jonsequitur** [comment]
They're not getting deprecated. It sounds like we need to clarify this. 

I think the documentation doesn't call them out as "positional" because **_all_** arguments are positional in System.CommandLine. 

An option argument (part of an `Option`) must always follow an option token:

```console
> myapp --verbose 123
                  ^-^
                  Option argument
```

A command argument is also positional but only relative to other command arguments, not to options.

So given either of these command definitions:

```cs
new RootCommand
{ 
    new Option<bool>("--verbose"),
    new Argument<int>(), 
    new Argument<string>()
}
```
or

```cs
new RootCommand
{ 
    new Argument<int>(), 
    new Argument<string>(),
    new Option<bool>("--verbose")
}

```
, the following two command lines are equivalent: 

```console
> myapp --verbose arg1 arg2 arg3
                  ^------------^
                  Command arguments

```
```console
> myapp arg1 arg2 arg3 --verbose 
        ^------------^
         Command arguments

```

Thoughts?

**Comment by Pxtl** [comment]
Okay, I think I get it now - I'm just coming from mentally looking at this as like C# method calls and PowerShell cmdlets, both cases where the partition between "arguments" and "options" aren't as firm.
