### ISSUE TITLE
Can't combine arguments with array option

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/command-line-api#1162]
Consider the following code:

```c#
var rootCommand = new RootCommand
{
    new Option<string[]?>("--config")
    {
        IsRequired = false,
    },
    new Argument<string>("source"),
    new Argument<string>("dest"),
};

rootCommand.Handler = CommandHandler.Create<string, string, string[]?>((source, dest, config) =>
{
    Console.WriteLine($"The value for 'source' is: {source}");
    Console.WriteLine($"The value for 'dest' is: {dest}");
    Console.WriteLine($"The number of config params is: {config?.Length ?? 0}");
});

rootCommand.Invoke(new[] { "--config", "abc", "--config", "def", "/src", "/dest" });
```

Running this code gives you:

```
Required argument missing for command: CommandLineReproducer
Required argument missing for command: CommandLineReproducer

Usage:
  CommandLineReproducer [options] <source> <dest>

Arguments:
  <source>
  <dest>

Options:
  --config <config>
  --version            Show version information
  -?, -h, --help       Show help and usage information
```

In my opinion, this should work.

What will work is if the `--config` options are put to the end, like so:

```c#
rootCommand.Invoke(new[] { "/src", "/dest", "--config", "abc", "--config", "def" });
```

However, I think, both calls should behave identical (especially since the error message in the first call - "Required argument missing for command: CommandLineReproducer" - is totally confusing).

**Comment by ksharshveer** [comment]
> Can't combine arguments with array option

I believe that this is not an issue. Let's first look at the following -

    rootCommand.Invoke(new[] { "/src", "/dest", "--config", "abc", "--config", "def" });
    rootCommand.Invoke(new[] { "/src", "/dest", "--config", "abc", "def"});
These two are equivalent. Note here that '--config' option here takes in the upcoming words as parameters to its array. Now, think about it, if any of the upcoming words are supposed to be required arguments, how would the program know that it's not a parameter to its option array.

Also, I think required arguments are supposed to be used in order, unless they are keyword arguments. Imagine 'src' and 'dest' to be used out of order, would result in disaster if you ask me.

Had the '--config' took a single value, instead of an array of values, then you would be able to mix and match things a little.

Now, I imagine why it would be allowed to use '--config' multiple times is so that you can add values to these options whenever you like with other options. For example -

    rootCommand.Invoke(new[] { "/src", "/dest", "--config", "abc", "--another-config", "alpha",  "beta", "--config", "def" });

Even though the options '--config' and '--another-config' are out of order, this would yield as follows -
'--config' will have values [ "abc", "def" ]
'--another-config' will have values [ "alpha", "beta" ]

Hopefully, this clears up the misunderstanding of why you think two missing required argument errors are confusing, because those are being interpreted as options for the '--config' array.

**Comment by skrysmanski** [comment]
> I believe that this is not an issue.

I disagree. It may be that you are *technically* correct but for an end user of the CLI the current behavior is totally confusing.

If you look at [existing CLIs](https://git-scm.com/docs/git-mv) it's customary to specify options before arguments:

    git mv <options>…​ <args>…​

I'm not that deep in how the `System.CommandLine` parser works but if you're right and `--config abc --config def` is the same as `--config abc def` than this would **always prevent array options *before* arguments** - which is an issue/problem in my opinion.

Maybe this behavior could be made configurable?

And are there examples for CLIs that use the `--config abc def` form? If not, this form could be dropped entirely.

**Comment by ksharshveer** [comment]
I've been digging around in the documentation, and conventions. From the [documentation](https://github.com/dotnet/command-line-api/blob/main/docs/Syntax-Concepts-and-Parser.md#options), it seems to use POSIX style, so I am hoping it also follows POSIX guidelines. Quote from documentation -

> While System.CommandLine can be configured to use these and other prefixes, the default is the POSIX style.

I found the following POSIX recommendations [link](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html). One of those which doesn't seem to align well here is the following -

> Options may be supplied in any order, or appear multiple times. The interpretation is left up to the particular application program.

I could not use an options multiple times, unless it is an array, and when it is an array, I couldn't use arguments after it.

I agree with you on using the array part, I also don't see a way to use arguments after an options array is used. However, I think we shouldn't use option that takes string array, rather, we should also follow standards for our application, and use something like comma-separated string for multiple values. The array option might be useful at the end to pass all arguments to a sub-command or something.

I also found [this](https://nullprogram.com/blog/2020/08/01/) nice article, "Conventions for Command Line Options". What I took away from it is that when following guidelines, there's unambiguous way of writing the commands, which this library seems to lack I think.

Consider the following, then I share a few things I find odd -
            var integerOption = new Option<int>(new[] { "--an-int", "-i" });
            integerOption.IsRequired = false;
            integerOption.Argument = new Argument<int>("integerValue", () => 1)
            {
                Arity = ArgumentArity.ZeroOrOne
            };
   
- When using arguments as `CommandLine -i -2`, parsing should fail because it is ambiguous. At no place in the setup did we say that the argument to `-i` is required, and yet parsing diagram shows `-2` is read as value to `-i`, when it could be another flag.
- When using settings where option is required, and arity is `ExactlyOne`, and arguments like `CommandLine --an-int 5`, based on the [documentation](https://github.com/dotnet/command-line-api/blob/main/docs/Syntax-Concepts-and-Parser.md#delimiters), the space delimiter should have been allowed, but the parsing fails.

I hope my little bit of research can be useful in current issue or finding new ones. On a side note, I had never used this library before using your code you mentioned in this issue. Also, you may find the parsing diagram feature useful, [here](https://github.com/dotnet/command-line-api/blob/main/docs/Features-overview.md#parse-preview).

**Comment by jonsequitur** [comment]
> And are there examples for CLIs that use the --config abc def form? If not, this form could be dropped entirely.

This is configurable using `Option.AllowMultipleArgumentsPerToken`. The property name here could probably be made clearer. The default is to allow `--config abc def` to parse as an array for option `--config`. There's a related issue that needs to be addressed to bring the single-arity behavior into line with POSIX expectations: #1083.

Also related:   #669.

**Comment by jonsequitur** [comment]
@ksharshveer Just a heads-up, there are a few API ambiguities that come into play with your example by setting the `Option.Argument` property. We're removing this property to make the behavior clearer. See PR #1148.

> When using arguments as CommandLine -i -2, parsing should fail because it is ambiguous. At no place in the setup did we say that the argument to -i is required, and yet parsing diagram shows -2 is read as value to -i, when it could be another flag.

The parser understands that `-2` is not a valid identifier as defined in your example, so in the context of this command line, it's unambiguous.

> When using settings where option is required, and arity is ExactlyOne, and arguments like CommandLine --an-int 5, based on the documentation, the space delimiter should have been allowed, but the parsing fails.

Can you elaborate on this? It seems to work for me but we might be doing something a little differently.

![image](https://user-images.githubusercontent.com/547415/106501114-8595b980-6477-11eb-919c-aa9d9856042d.png)

**Comment by ksharshveer** [comment]
Hello @jonsequitur I will try to explain my point of view. 

**First part -**
Here's what I did, I made `-2` a flag, by using -

            var flagOption = new Option<bool>("-2");
            parent.Add(flagOption);

Invocations - 

            parent.Invoke(new string[] { "[parse]", "-i -2" });
            parent.Invoke(new string[] { "[parse]", "-2" });

Output -
[ CommandLine [ -i <-2> ] ]
[ CommandLine [ -2 <True> ] *[ --an-int <1> ] ]

Like I said earlier, `-i` is supposed to be optional, but when specified it absolutely expects a value. In this case it thinks `-2` is a value not a flag. By the way, when used without any arguments except `-i`, it works, but behaviour is not what I expect. We have set the getDefaultValue, but when used without passing a value, it overrites our default with the type default value. 0 in this case.

**Elaboration on second part -**
This should be complete code to reproduce the output I get -
 
       static RootCommand parent = new RootCommand("parent");

        static void Main(string[] args)
        {
            var integerOption = new Option<int>(new[] { "--an-int", "-i" });
            integerOption.IsRequired = true;
            integerOption.Argument = new Argument<int>("integerValue")
            {
                Arity = ArgumentArity.ExactlyOne
            };
            parent.Add(integerOption);

            parent.Invoke(new string[] { "[parse]", "--an-int 5" });
            parent.Invoke(new string[] { "[parse]", "--an-int=5" });

            Environment.Exit(2);

Output -
![ CommandLine ]   ???--> --an-int 5
[ CommandLine [ --an-int <5> ] ]

Like I mentioned that in the docs, space is a valid delimiter for use in long option, however, the parse diagram shows error. We can see that the `=` delimiter works just fine.

**Comment by jonsequitur** [comment]
> Like I said earlier, -i is supposed to be optional, but when specified it absolutely expects a value. In this case it thinks -2 is a value not a flag.

The intention of `Opton.IsRequired` is to indicate whether the option (with whatever arguments it defines) is required. It doesn't change the parsing of the option's arguments in any way. So for example if you were to set `interOption.IsRequired = true`, then any command line not containing either `-i` or `--an-int` would produce an error. When one of those is specified, the `Option.Argument`'s arity (in the case of `int` this defaults to `ArgumentArity.ExactlyOne`) will be enforced, so the following token should strictly be considered an argument to that option.  

The distinction between the ` ` (space) and `=` argument delimiters looks surprising. I'll dig into whether that's a bug.

> By the way, when used without any arguments except -i, it works, but behaviour is not what I expect. We have set the getDefaultValue, but when used without passing a value, it overrites our default with the type default value. 0 in this case.

Can you provide the precise command line input and parse result?

**Comment by jonsequitur** [comment]
I would also recommend changing your code to this:

```csharp
var integerOption = new Option<int>(new[] { "--an-int", "-i" }, getDefaultValue: () => 1);
integerOption.IsRequired = false;
```

Setting the argument will soon be disallowed, as it presents a few gotchas because you may overwrite values passed in the constructor.

**Comment by jonsequitur** [comment]
I spotted an issue with the invocations in your last code sample. 

You should change this:

```csharp
parent.Invoke(new string[] { "[parse]", "--an-int 5" });
parent.Invoke(new string[] { "[parse]", "--an-int=5" });
```

to this: 

```csharp
parent.Invoke( "[parse] --an-int 5" );
parent.Invoke( "[parse] --an-int=5" );
```

If you pass an array, it assumes that the string has already been split into appropriate tokens, so the issue with the space delimiter is that your first invocation is the equivalent of passing this on the command line:

```console
> [parse] "--an-int 5"
```

**Comment by ksharshveer** [comment]
Thanks @jonsequitur for clearing things up. I didn't knew that invoke behaved that way for string array vs a complete string. For the other part, it doesn't matter now, since the Option.Argument property will likely be removed.

**Comment by jonsequitur** [comment]
You're welcome. I was just making sure to understand a bunch of potential usability problems and/or bugs in this thread, and (aside from missing docs), I think we can consider the default value of `true` for `Option.AllowMultipleArgumentsPerToken` to be a design bug. Even though fixing it is a breaking change, the fact that the convention is not very common might justify the change.

**Comment by skrysmanski** [comment]
@jonsequitur Thanks for all the information. Setting `Option.AllowMultipleArgumentsPerToken` to `false` indeed solve the problem for me.

The question now is what to do with this issue? I would close it since my problem is now solved. Or do you want to keep it open?

**Comment by Balfa** [comment]
> The default for this setting is to allow `--config abc def` to parse as an array for option `--config`. Seeing this example makes me think we should swap the default for this property

@jonsequitur , I strongly agree with this change in default! Any idea on if/when?

**Comment by jonsequitur** [comment]
The default for `Option.AllowMultipleArgumentsPerToken` is `false` in the latest release.

**Comment by Balfa** [comment]
Ah, excellent, I was hoping to check but haven't had a chance to upgrade yet! Thanks 👍
