### ISSUE TITLE
Help text aligning not working for custom IConsole

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/command-line-api#1184]
When providing one's own `IConsole` implementation, help text aligning no longer works.

Consider this code snippet:

```c#
var rootCommand = new RootCommand
{
    new Option<bool>("--force", "Suppresses prompting to confirm you want to overwrite an existing destination file. With some very long text that make it necessary to break this line even though it does not provide any additional information."),
    new Option<int>("--value", "Another value"),
};

rootCommand.Invoke(new [] { "--help" });
```

Running this code results in something like this:

![regular](https://user-images.githubusercontent.com/914747/106623555-07b7d800-6575-11eb-99a3-8fcbc33ae7bf.png)

However, if an `IConsole` object is passed to `Invoke`:

```c#
rootCommand.Invoke(new [] { "--help" }, myConsole);
```

the output changes to this:

![broken](https://user-images.githubusercontent.com/914747/106624229-b6f4af00-6575-11eb-96b6-2669927d1165.png)

Note how the wrapping and aligning of the help text of `--force` no longer works.

As far as I can tell, the problem comes from this code:

https://github.com/dotnet/command-line-api/blob/98a466e60db38e00bd747e3a27c21ae54b1154ec/src/System.CommandLine/Help/HelpBuilder.cs#L831-L841

The problem is that `GetConsoleWindowWidth()` is not part of `IConsole` - thus users with custom `IConsole` implementations/wrappers have no way of getting proper help text aligning/wrapping.

The most straight way forward to solve this would be to simply add `GetConsoleWindowWidth()` to `IConsole` - but this would be a breaking change.

**Comment by skrysmanski** [comment]
I've been thinking a little bit about this and I think the new member should be `int?` (not just `int`) - so implementers can return `null` for consoles that don't have a width (like logs or similar):

```c#
int? ConsoleWidth { get; }
```

I also think the member should be a property rather than a method.

**Comment by jonsequitur** [comment]
The `IConsole` interface deliberately doesn't have properties such as width and cursor position, in order to more accurately represent the core console (as opposed to terminal) concept. By the definition we're using (and there's admittedly a lot of confusion around this):

_Console_: stdin, stdout, stderr
_Terminal_: A stateful app for communicating over a console interface.

The statefulness is the key here and it's the source of some common gotchas with `System.Console` which conflates these two concepts. If you redirect output, for example, then trying to get the width or cursor positions will throw. These thing's don't exist unless there's a local application on the other end of the stream. 

We've sketched `ITerminal` over [here](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine.Rendering/ITerminal.cs) but more work is needed, including where/when these interfaces can best be surfaced.

That's a bunch of background. I don't have a suggestion for a solution yet, though. My hunch is it would be more in the direction of allowing help to be more customizable, without getting into the console/terminal confusion.

**Comment by svengeance** [comment]
> My hunch is it would be more in the direction of allowing help to be more customizable, without getting into the console/terminal confusion. 

For what it's worth I like this idea. I was looking at how to customize the helptext a bit myself, and I think it would be neat if the formatting was derived **not** from any one implementation (whether terminal or not), but rather from an expose/configurable class. Expecting people to read the technical background of this project to understand the different is a long shot.

**Comment by jonsequitur** [comment]
I believe the latest release should resolve this issue. You can now set the console `maxWidth` via an optional parameter to the constructor for `HelpBuilder`.
