### ISSUE TITLE
Enable github actions to avoid regressions

### ISSUE THREAD

**Issue by henrygab** [dotnet/command-line-api#1242]
<details><summary>There appear to be implied contracts, and occasionally regressions</summary><P/>

Examples that seem like they would benefit from defining unit tests for expected behaviors:

* Make multiple arity option overflow behavior consistent with argument behavior #1143
* Options not being positional, command arguments being positional #1157
* ParseArgument delegates called when argument used without token #1182
* Unintentional exposure of new (e.g., internal) types #1213
* What result with arity max > 1, and command line: `app.exe --foo 1 2 3 cmd --foo 5 6 7` #1219
* Regression causing `null` for collection arguments #1233
* Support for `--` to explicitly stop parsing options, and pass remaining items are parameters #1238

</details>

Please use github actions (or other CI capability) to automatically run unit tests on PRs.

Even after the v2 API stabilizes, it's necessary to ensure that the **_implied behaviors_** are stable, also.
Unit tests are a relatively easy way to reduce the likelihood of breaking clients in at least three ways:
1. They define the behaviors that the library provides (beyond the API)
2. When used with CI, they ensure those behaviors don't regress
3. Adding a new unit test defines a new behavior that clients can rely upon

Requiring unit tests to pass, prior to merging a pull request, goes a **_long_** way to ensuring stability.  Github's makes this easy via the repository's [Actions](https://github.com/dotnet/command-line-api/actions) tab.

**Comment by jonsequitur** [comment]
Like other .NET libraries, we use use [Arcade](https://github.com/dotnet/arcade) for CI and other build validations, security checks, package signing, and so on. Our PR validations include tests runs of debug and release builds across Ubuntu, macOS, and Windows, including a suite of about 1200 tests.

The tests are intended to verify and document intentional behaviors and prevent regressions. They're not intended at this point to lock in an API contract, since we haven't reached the [2.0 GA milestone](https://github.com/dotnet/command-line-api/milestone/1). So I think that most of the bugs you've highlighted are either deliberate changes to the contract and/or behavior, or emergent behaviors arising from that work. 

As part of the milestone, we should absolutely add approval tests to ensure that changes to the public API surface are highly visible and deliberate.

**Comment by jonsequitur** [comment]
@henrygab, [here's](https://github.com/dotnet/interactive/pull/1200/files#r605325139) one approach we could use to pin the public API surface in a readable way.
