### ISSUE TITLE
Different "latest" release versions on Github / nuget.org

### ISSUE THREAD

**Issue by HelOWeen** [dotnet/command-line-api#1251]
I'm a bit confused by the version discrepancy here and the version listed over at NuGet.

The release page here (_at the time of writing_) lists [2.0.0-beta1.20371.2](https://github.com/dotnet/command-line-api/releases/tag/2.0.0-beta1.20371.2) as the latest release, whereas NuGet offers [2.0.0-beta1.20574.7](https://www.nuget.org/packages/System.CommandLine/2.0.0-beta1.20574.7) as the latest release.

**Comment by perlun** [comment]
Thanks for raising this @HelOWeen! :pray: I also noted that there is even a newer version available now: https://www.nuget.org/packages/System.CommandLine/2.0.0-beta1.21216.1. Didn't even think to look there since I assumed the releases listed here was accurate and that no release had been made since June 2020.

I do agree that it's definitely a bit confusing that there are releases that have been made without a tag/release notes being published. Maybe @jonsequitur could get someone to deal with this?

**Comment by jonsequitur** [comment]
There is a release for this version: https://github.com/dotnet/command-line-api/releases/tag/v2.0.0-beta1.21216.1

**Comment by perlun** [comment]
Hmm, why didn't I see that one? :see_no_evil: Thanks, you're right @jonsequitur.
