### ISSUE TITLE
Redesign IConsole abstraction

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#132]
`IConsole` was introduced for testing purposes and shouldn't grow to include the responsibilities of `System.Console`. 

* We need an abstraction for writing and reading standard I/O. 
* We probably also need (in a separate mechanism) an abstraction for setting colors, manipulating cursor position, etc.

What should these abstractions look like?

**Comment by drewburlingame** [comment]
I would find it helpful if IConsole was abstracted from System.CommandLine so that I could use it instead of Console but without the dependency of System.CommandLine.  It would be great to use that with the Rendering work as well.  This would also be an opportunity to pull efforts like ReadLine to be pulled in and better maintained by a community.
