### ISSUE TITLE
How could I make my argument optional?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/command-line-api#1384]
I'm trying to make my argument optional by setting the argument arity with `ArgumentArity.ZeroOrOne`, but could not make it work, could you please help.

My code sample is as follows:

``` c#
var command = new RootCommand("h");
var methodArgument = new Argument<HttpMethod>("method", "Request method");
methodArgument.Arity = ArgumentArity.ZeroOrOne;
command.AddArgument(methodArgument);
var urlArgument = new Argument<string>("url", "Request url");
urlArgument.Arity = ArgumentArity.ExactlyOne;
command.AddArgument(urlArgument);

var schemaOption = new Option<string>("--schema", ()=> "http", "schema");
command.AddOption(new Option(new[] { "-v", "--verbose" }, "Verbose"));
command.AddOption(schemaOption);

var parseResult = command.Parse(args);

Console.WriteLine("----- Tokens ------");
foreach (var token in parseResult.Tokens)
{
    Console.WriteLine($"{token.Type}: {token.Value}");
}
Console.WriteLine("------------------");

Console.WriteLine($"Schema value: {parseResult.ValueForOption(schemaOption)}");
Console.WriteLine($"Request：{parseResult.ValueForArgument(methodArgument)} {parseResult.ValueForArgument(urlArgument)}");
```

When I specific the method argument, it works, but failed when I exec without method argument

![image](https://user-images.githubusercontent.com/7604648/130345461-42eade97-3f09-4609-9669-a03be4155171.png)

Sample repository: <https://github.com/WeihanLi/SamplesInPractice/blob/d6c046dc67234d7422d509e2acbfabae16847133/CommandLineAppSamples/GetStarted/Program.cs>

**Comment by jonsequitur** [comment]
This is by design. The parser will try to fill the earlier positional arguments before moving on to the later ones. "Optional" arguments therefore need to come at the end.

One way that could work to get the command line interface you're looking for is to model `get` as a subcommand instead of an argument. If your root command and the `get` subcommand both have the same handler, then you will have effectively defined `get` as the default behavior. (If it's useful, this also means that for other `HttpMethod` values, you could have options and arguments that only apply to those.)

**Comment by WeihanLi** [comment]
Great thanks for your reply @jonsequitur
