### ISSUE TITLE
Is there a way to get to the help text produced from the —help option from within the application?

### ISSUE THREAD

**Issue by llu23** [dotnet/command-line-api#1392]

**Comment by elgonzo** [comment]
Use the [HelpBuilder](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Help/HelpBuilder.cs) class. Note the parameters in its constructor:
```C#
public HelpBuilder(IConsole console, Resources resources, int maxWidth = int.MaxValue)
```
For the _resources_ parameter, you can usually use `Resources.Instance`.
For the _console_ parameter, write a class that implements [IConsole](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/IConsole.cs), and which will receive the generated help text.

If you want to have the help text as a simple string, your _IConsole_ implementation could perhaps be as simple as:
```C#
using System.CommandLine;
using System.CommandLine.IO;

class StringConsole : IConsole
{
    private readonly StringWriter _out = new StringWriter();
    private readonly StringWriter _error = new StringWriter();

    public string GetOutText() => _out.ToString();
    public string GetErrorText() => _error.ToString();

    IStandardStreamWriter IStandardOut.Out => _out;
    bool IStandardOut.IsOutputRedirected => false;

    IStandardStreamWriter IStandardError.Error => _error;
    bool IStandardError.IsErrorRedirected => false;

    bool IStandardIn.IsInputRedirected => false;


    private class StringWriter : IStandardStreamWriter
    {
        private readonly StringBuilder _sb = new StringBuilder();

        public override string ToString() => _sb.ToString();

        void IStandardStreamWriter.Write(string value) => _sb.Append(value);
    }
}
```
Finally, use the `HelpBuilder.Write(ICommand command)` method to generate the help for whichever of your commands you like. Using my little _StringConsole_ class from above, this could look like:
```C#
var strConsole = new StringConsole();
var helpBld = new HelpBuilder(strConsole, Resources.Instance, 120);

helpBld.Write(yourRootCommand);
var rootCmdHelpText = strConsole .GetOutText();
```

**Comment by jonsequitur** [comment]
Thanks, @elgonzo!

**Comment by llu23** [comment]
Thank you @elgonzo

**Comment by llu23** [comment]
With the solution that @elgonzo provided above, it doesn't actually print out the help for the subcommands.  It looks like to request help for a subcommand, its required to further explicitly request it (ie.  myapp.exe subCommand1 /?).   So, this would mean I would need to determine which command was requested, then get the command instance and pass it to helpBld.Write(subCommand);   Is there already a way to get the help text by passing it the args?

**Comment by elgonzo** [comment]
If your intention is to redirect/obtain System.Commandline's output based on the provided commandline arguments, you could provide your custom _IConsole_ implementation to the Invoke/InvokeAsync method used to pass the commandline arguments to System.Commandline. The provided _IConsole_ instance will then receive the output generated by System.Commandline.

**Comment by llu23** [comment]
Thank you @elgonzo.  The help output for a subcommand displays:
Usage: 
MyApp [options] subCommand1
Options:
....

It should be :
MyApp subCommand1 [options]

**Comment by elgonzo** [comment]
You could probably use a _CommandLineBuilder_ for this. It has an extension method allowing to define the help layout (i.e., the help sections to be printed):
https://github.com/dotnet/command-line-api/blob/32bce63b0f6ae5244b189b86b9ff7c632ca26027/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L434-L444

The `HelpBuilder` class offers a number of static members providing _HelpDelegate_'s for the different sections. As reference and illustration how you could define your own _IEnumerable&lt;HelpDelegate&gt;_ layout, here the definition of the default help layout:
https://github.com/dotnet/command-line-api/blob/32bce63b0f6ae5244b189b86b9ff7c632ca26027/src/System.CommandLine/Help/HelpBuilder.cs#L77-L88



All in all, if for example you would like to drop the synopsis from the help output, you could then process your commandline arguments like this (unverified pseudo-code):
```C#

    IEnumerable<HelpDelegate> MyCustomHelpLayout() 
    { 
        // I do not want synopsis
        // yield return SynopsisSection(); 

        yield return CommandUsageSection(); 
        yield return CommandArgumentsSection(); 
        yield return OptionsSection(); 
        yield return SubcommandsSection(); 
        yield return AdditionalArgumentsSection(); 
    } 


    var parser = new CommandLineBuilder(myRootCommand)
        .UseHelp(MyCustomHelpLayout())
        .UseDefaults()
        .Build();

    parser.Invoke(args, myCustomConsole);
```
Using a _CommandLineBuilder_, you could alternatively pass your custom _IConsole_ implementation to the _CommandLineBuilder_ using its [_ConfigureConsole_ method](https://github.com/dotnet/command-line-api/blob/32bce63b0f6ae5244b189b86b9ff7c632ca26027/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L99-L116) instead of passing it to the _Invoke_ method:
```C#
    var parser = new CommandLineBuilder(myRootCommand)
        .ConfigureConsole(bindingCtx => myCustomConsole)
        .UseHelp(MyCustomHelpLayout())
        .UseDefaults()
        .Build();

    parser.Invoke(args);
```

**Comment by llu23** [comment]
this isn't in 2.0.0-beta1.21308.1

**Comment by elgonzo** [comment]
You can get more recent daily builds from the daily build nuget feed (see to the [readme.md](https://github.com/dotnet/command-line-api#readme) for the actual URI of the daily builds feed).

With regard to the next official (pre-)release, there was a recent topic about this: https://github.com/dotnet/command-line-api/issues/1482. There is also an overview of the milestones tracked for the next (pre-)release here: https://github.com/dotnet/command-line-api/milestone/1
