### ISSUE TITLE
Cannot parse empty string as argument of option

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/command-line-api#1551]
With System.CommandLine 2.0.0-beta2.21617.1, if I define a command like this

```C#
using System;
using System.CommandLine;

internal static class Program
{
    private static int Main(string[] args)
    {
        var execPrefixOption = new Option<string>("--exec-prefix", getDefaultValue: () => "/usr/local");
        var rootCommand = new RootCommand()
        {
            execPrefixOption,
        };
        rootCommand.SetHandler(
            (string execPrefix) => Console.WriteLine(execPrefix + "/bin"),
            execPrefixOption);
        return rootCommand.Invoke(args);
    }
}
```

and run the program with arguments `--exec-prefix ""`, then I expect it to override the default value "/usr/local" with an empty string, but it instead reports an error:

> Required argument missing for option: '--exec-prefix'.

`--exec-prefix=""` has the same result.

The <https://github.com/dotnet/command-line-api/issues/1533> fix in <https://github.com/dotnet/command-line-api/pull/1536/commits/260a559f5a5f4ec8d075a7accec1f2a185528a43> looks related, but I don't know whether this has worked in earlier versions, either.

**Comment by elgonzo** [comment]
> but I don't know whether this has worked in earlier versions, either.

Both `--exec-prefix ""` as well as `--exec-prefix=""` still worked in 2.0.0-beta1.21525.1.

Later versions changed the behavior of `--exec-prefix=""` but left `--exec-prefix ""` still intact for a while.

In my subjective and cheap opinion, changing the behavior of `--exec-prefix=""` and then later also of `--exec-prefix ""` was the wrong call.

I see no good reason to prohibit a user from providing an empty commandline argument like `--exec-prefix ""`.

Since `--exec-prefix=""` as well as ``--exec-prefix:""`` are supposed to be synonymous with `--exec-prefix ""`, for consistency reasons both `--exec-prefix=""` and ``--exec-prefix:""`` should be allowed as well.

Which in the end means, due to how commandline arguments are processed and fed into the _args_ parameter of the _Main_ method (at least on Windows), that `--exec-prefix=` and `--exec-prefix:` should be allowed to, representing the option with an implied empty string. I would find this the lesser evil than just outright outlawing empty options arguments. (Just my two cents, of course...)

**Comment by ilyapalkin** [comment]
I face the similar error on `2.0.0-beta4.22272.1` when provide `--exec-prefix=""`

My code:
```
        var execPrefix = new Option<string>("--exec-prefix",  description: "Exec prefix");
        ...
        var rootCommand = new RootCommand()
        {
            execPrefix ,
            ...
        };
        var parsed = rootCommand.Parse(args);
        if (!parsed.Errors.Any())
        {  ...  }
        else {
            ...
            // print errors returns "Required argument missing for option: '--exec-prefix'."
        }
```

How to handle empty srtring as a parameter valu?
