### ISSUE TITLE
Add SetHandler overrides for command returning an exit code

### ISSUE THREAD

**Issue by dgolub** [dotnet/command-line-api#1570]
The original `CommandHandler.Create` API supports handler functions that return `int` so that the command can return an exit code other than 0 if there's an error.  It looks like the new `SetHandler` API requires that the handler function return either `void` or `Task`.  Can we add overrides for `int` and `Task<int>` before GA?  Thanks!

**Comment by jonsequitur** [comment]
You can always take in an `InvocationContext` in your handler and set `InvocationContext.ExitCode`.

**Comment by baronfel** [comment]
We had this same situation on the `dotnet` CLI, and the approach we took was to:

* make our own ICommandHandler that fit the lambda signature we needed and transformed our lambdas into `Task<int>` returns
* made an `SetHandler` extension method on the `Command` type (like is already done in this repo) for our specific use case to create our ICommandHandler instead

so not a ton of work, but a slight change in the expected API.

**Comment by jonsequitur** [comment]
It's hard to know what's the right number of overloads. I think there are too many and it makes intellisense a bit confusing. (The source generator approach we've been experimenting with is basically just generating the exact signature you need.)

Doing away with return types (other than simple `Task` to support async) can help keep this under control and leaves the door open to have other return types from handlers, e.g. data objects that a rendering layer can then present in the console.

**Comment by tmds** [comment]
Commands are expected to handle failure situations and turn them into exit codes.
I'm surprised `SetHandler` API doesn't foresee this.

The current API encourages throwing exceptions over returning exit codes.
That gives a bad UX for the end-user.

**Comment by tmds** [comment]
> You can always take in an InvocationContext in your handler and set InvocationContext.ExitCode.

@jonsequitur does that mean I can't use any of the overloads that take a strongly-typed `Action<T1, ..., Tx>`?

**Comment by jonsequitur** [comment]
In beta 4, in order to keep the combinatorial overload explosion to a minimum, we only provide two flavors of `SetHandler`:

* Those that bind parameters for you, like this:

    ```csharp
    var option = new Option<int>("-i");
    // ...
    command.SetHandler(i => { }, option);
    ```

    (These parameters can include types like `CancellationToken` or `InvocationContext` using a custom binder, which we'll simplify in beta 5 by introducing something like `Bind.FromServiceProvider<T>()`.)

* Those that provide an `InvocationContext`, like this:

    ```csharp
    var option = new Option<int>("-i");
    // ...
    command.SetHandler(context => 
    { 
        var i = context.ParseResult.GetValueForOption(option);
    });
    ```

> The current API encourages throwing exceptions over returning exit codes.

Exceptions are caught and translated into non-zero exit codes by default, or you can assign the exit code to `InvocationContext.ExitCode`.

Ok, so where does that leave us? Right now there are 20 `SetHandler` overloads, accepting these delegate types:

* `Action`
* `Action<InvocationContext>`
* `Action<T1>` through `Action<T1, T2, T3, T4, T5, T6, T7, T8>`
* `Func<Task>`
* `Func<InvocationContext, Task>`
* `Func<T1, Task>` through `Action<T1, T2, T3, T4, T5, T6, T7, T8, Task>`

If you return `Task<int>` from any of the `Func*` overloads, it will be used to set the exit code:

```csharp
command.SetHandler(i =>
{
    return Task.FromResult(123);
}, option);
```

The problem here is that you get a compiler error if you try to use an `async` delegate:

```csharp
// THIS DOES NOT COMPILE IN BETA 4
command.SetHandler(async i =>
{
    return 123;
}, option);
```

Supporting directly returning an exit code would double the number of `SetHandler` overloads, adding:

* `Func<int>`
* `Func<InvocationContext, int>`
* `Func<T1, int>` through `Action<T1, T2, T3, T4, T5, T6, T7, T8, int>`
* `Func<Task<int>>`
* `Func<InvocationContext, Task<int>>`
* `Func<T1, Task<int>>` through `Action<T1, T2, T3, T4, T5, T6, T7, T8, Task<int>>`

This would be a usability improvement in some ways and not in others. IntelliSense is already quite crowded for this method. 

Adding support for directly returning exit codes would nearly double this. We're looking for a more elegant solution and would love suggestions. This is related to #1776 so I'll add these details there.

**Comment by dgolub** [comment]
Right, which is why a number of us have been asking for a simple way to return an error code.

**Comment by dgolub** [comment]
I would suspect that there are developers who have strong preferences for both, much like with `int main()` and `void main()` in C/C++.

**Comment by tmds** [comment]
Maybe we should use enums to represent command results?

The `SetHandler` methods can have an `enum` constraint:
```cs
    void SetHandler<T>(Func<Task<T>> handle) where T : System.Enum;
    void SetHandler<T>(Func<T> handle) where T : System.Enum;
    ...
```
We can include a default `enum`:
```cs
enum CommandResult
{
    Success = 0,
    Failure = 1
}
```

Example with a custom `enum`:
```cs
enum MyCommandStatus
{
     Success = 0,
     Failure1 = 100,
     Failure2 = 200
}
command.SetHandler(() => MyCommandStatus.Failure1);
```

**Comment by tmds** [comment]
> There's no way to constrain it to enums in which the underlying type is int.

Right, we can't constrain the `enum` to have underlying `int` type. This is more an implementation concern.

> it would be weird if one had to define an enum type just to satisfy SetHandler.

The alternatives are to use const fields or literal constants.

**Comment by tmds** [comment]
That some of these work with `int` doesn't mean `SetHandler` needs to do the same. Similar to how ASP.NET doesn't make you work with `HttpContext` when implementing an endpoint.

Anyway, I'll be happy to have a directy way to control the exit code, be it an `int` or an `enum`.

The maintainers can decide what they want.

**Comment by tmds** [comment]
@jonsequitur if you decide what the API should be, I can look into implementing it, if you want.
