### ISSUE TITLE
IConsole is not thread safe

### ISSUE THREAD

**Issue by remcoros** [dotnet/command-line-api#1590]
I just found that the IConsole (and related TextWriter wrappers) are not threadsafe:

A console tool (net6.0) that runs multiple operations in parallel using Task.Run(..) and write progress using IConsole.WriteLine

>result from process1\r\n
>result from process2\r\n
>result from process3result from process4\r\n
>\r\n
>result from process5\r\n

Initially, I thought it was an issue with System.Console (see https://github.com/dotnet/runtime/issues/53751).

After trying to repro this, I found this in System.Commandline StandardStreamWriter: https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/IO/StandardStreamWriter.cs#L59

System.Console uses a Synchronised TextWriter to avoid this. System.Commandline might need to do the same. Or do one call to "Write(message + Env.Newline)" instead of two separate calls on the Console.

**Comment by jonsequitur** [comment]
Nice find! 

To clarify what needs to be fixed here, the specific issue isn't with `IConsole`, it's with the two calls you pointed out in the extension method you linked to.

The default implementation of `IConsole` is `SystemConsole` [here](https://github.com/dotnet/command-line-api/blob/e098c0d00ad7bbbe1718c0a9f24f1a8f461817f3/src/System.CommandLine/IO/SystemConsole.cs#L0-L1) which is a simple pass-through to `System.Console` so thread safety is maintained. The in-memory `TestConsole` isn't threadsafe, by design.

**Comment by remcoros** [comment]
Already sent a PR ;)
