### ISSUE TITLE
Using DirectoryInfo as Option appears to add app path to the FullName property

### ISSUE THREAD

**Issue by shaggygi** [dotnet/command-line-api#1644]
While `DirectoryInfo` is not shown as a supported option like `FileInfo`, I tried today and seems to take it and can be read from the `OriginalPath` property.  However, the `FullName` seems to put the path where the app is running instead.

For example, I passed in the string "X:\" and the `OriginalPath` is the same.  `FullName` shows something like...

```
"X:\\VisualStudio\\src\\MyApp\\bin\\Debug\\net6.0\\\""
```

It looks like the parent is also set as...

```
"X:\\VisualStudio\\src\\MyApp\\bin\\Debug\\net6.0"
```

If this is not supported, it would be a nice-to-have.

Thanks for reviewing.

**Comment by elgonzo** [comment]
Your issue is entirely unrelated to System.CommandLine.
What you observe is the bog-standard behavior of DirectoryInfo/FileInfo.

`X:` in itself is not a directoy. It's just a drive letter, without specifiying any directory on that drive.
Thus, when only providing a drive letter to DirectoryInfo/FileInfo, the current/last working directory with respect to the specified drive is used-- and this is what you see in `FullName`.

You can verify this simply for yourself by just instantiating a DirectoryInfo/FileInfo "manually" without involving System.CommandLine at all. Run something like this two-liner in your _Main_ method and see what you get:
```C#
var di = new DirectoryInfo("X:");
Console.WriteLine(di.FullName);
```

**Comment by shaggygi** [comment]
@elgonzo Oh, I see now.  I thought that seemed a little odd.  Thank you for the info.  Learn something new every day.  👍 😄
