### ISSUE TITLE
Endless loop in PageResultVisitor.ValidateCommandResult()

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/command-line-api#1687]
With `2.0.0-beta3.22114.1` I'm getting an endless loop in `PageResultVisitor.ValidateCommandResult()`.

The trimmed down version of the method looks like this:

```c#
var commandToCheckForRequiredOptions = command;
ParentNode? currentNode = null;

while (commandToCheckForRequiredOptions is not null)
{
    ...

    if (currentNode is not null)
    {
        commandToCheckForRequiredOptions = currentNode.Next?.Symbol as Command;
        if (commandToCheckForRequiredOptions is null)
        {
            currentNode = null;
        }
    }
    
    ...
}
```

What happens here is basically the following:

1. `currentNode` is set to a non-null value in one of the iteration
2. the while loop restarts
3. `commandToCheckForRequiredOptions` is set from `currentNode.Next?.Symbol as Command`
4. the result is not-null, thus `currentNode` keeps its value
5. the while loop restarts
6. since `currentNode` hasn't changed, `commandToCheckForRequiredOptions` will be set to the exact same value as in the previous iteration (`currentNode.Next` has also not changed)

Thus the loop never terminates.

I've written an (opinionated) wrapper around System.CommandLine. With this wrapper I can always reproduce this problem. However, I haven't been able to reproduce this problem with just System.CommandLine code.

I've also noticed that the implementation of this method is differently on the main branch (most likely due 3cb430c773e946bc8500416d2cc68a745fafd7fc).

So, before investigating further, I wanted to check how you guys want to handle this problem? "Ignore" it since the implementation on main is already different? Backport the change from main?

Also, maybe one of you has some clever idea/pointer on how I could figure out the root cause of this problem?

**Comment by elgonzo** [comment]
> "Ignore" it since the implementation on main is already different?

I guess that's the reasonable course of action.

> Backport the change from main?

I do not really understand what you are trying to ask. Since 2.0.0-beta3.22114.1 is a _beta_ version, it's not supposed to be a lasting release. Thus, in my entirely subjective (2c worth of) opinion, backporting doesn't really make sense. What would backporting the change to 2.0.0-beta3.22114.1 result in, if not another new beta? How would "backporting" differ from just releasing a new beta? (And newer betas/daily builds are already available; see last paragraph of my comment.)

> Also, maybe one of you has some clever idea/pointer on how I could figure out the root cause of this problem?

Unless you want to take this as a personal challenge for your own enjoyment, there is little point in trying to figure this out based on 2.0.0-beta3.22114.1, given that the current implementation of the ValidateCommandResult method substantially differs from its older and outdated implementation you refer to.

Instead, i would suggest to use a newer beta version / daily build of the library. Daily builds can be obtained from the daily builds nuget feed mentioned in the project's [readme.md](https://github.com/dotnet/command-line-api) (https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json). Newest build as of time of writing my comment is 2.0.0-beta3.22173.1. Then, if the problem still occurs with the newest beta, you or others might spend some elbow grease investigating the issue based on the current code base. :-)

**Comment by jonsequitur** [comment]
If you can come up with a simple repro on the latest package version, we'll fix it. 

The `ValidateCommandResult` method no longer contains a `while` loop. Maybe that was the source of the problem?

**Comment by skrysmanski** [comment]
Thanks for all your feedback. I didn't really think the whole release cycle for System.CommandLine through. So it didn't really occur to me that I may *not* have to wait half a year before the next version. Sorry for the confusion.

> Instead, i would suggest to use a newer beta version / daily build of the library.

That's a great idea. I will try this. If the newest daily build fixes this problem, I'll close this issue.

**Comment by skrysmanski** [comment]
I've just switched to version `2.0.0-beta3.22173.1` and the problem no longer exists.

Now the only question that remains is: When will this version (or a later one) land on nuget.org?

**Comment by skrysmanski** [comment]
@jonsequitur That sound great. I'm closing this issue since there's nothing more to do.
