### ISSUE TITLE
Support for multiple values for an option: --option value1 value2 ?

### ISSUE THREAD

**Issue by sorin-nistor** [dotnet/command-line-api#1713]
I have this sample command setup:
```
        public static async Task<int> Main(string[] args)
        {
            RootCommand appCommand = new RootCommand("Demo");

            Command cmd = new Command("cmd1", "Sample command");
            appCommand.AddCommand(cmd);

            Option<double[]> size = new Option<double[]>(
                aliases: new string[] { "-s", "--size" },
                getDefaultValue: () => new double[2],
                description: "Array of 2 numbers, width and height");
            size.Arity = new ArgumentArity(2, 2);
            cmd.AddOption(size);

            cmd.SetHandler<double[]>(Run, size);

            return await appCommand.InvokeAsync(args);
        }

        private static void Run(double[] size)
        {
            Console.WriteLine($"width: {size[0]}; height: {size[1]}");
        }
```
This line works as expected:
`myapp cmd1 --size 1000 --size 2000`
Based on the documentation and some blog posts this command line should also work:
`myapp cmd1 --size 1000 2000`
But I always get this error:
`Required argument missing for option: '--size'.`
`Unrecognized command or argument '2000'.`
Is this style of command line supported or I'm missing some setting?
I'm using the nuget package 2.0.0-beta3.22114.1

**Comment by elgonzo** [comment]
Allowing multiple values for a single option on the commandline _was_ the default behavior, but has been changed because that behavior could lead to ambiguities when commandline interfaces become a little more complex. (see related discussion: https://github.com/dotnet/command-line-api/issues/1162)

However, if you desire this behavior, you can explicitly enable it by setting the `AllowMultipleArgumentsPerToken` property on the respective option(s) to _true_:
```C#
Option<double[]> size = new Option<double[]>(
    aliases: new string[] { "-s", "--size" },
    getDefaultValue: () => new double[2],
    description: "Array of 2 numbers, width and height"
) {
    Arity = new ArgumentArity(2, 2),
    AllowMultipleArgumentsPerToken = true
};
```
FYI: The documentation is in the process of being integrated with the .NET documentation over at docs.microsoft.com and contains up-to-date information there. See here: https://docs.microsoft.com/en-us/dotnet/standard/commandline, and with respect to arity specifically: https://docs.microsoft.com/en-us/dotnet/standard/commandline/syntax#argument-arity

**Comment by sorin-nistor** [comment]
Thank you.
