### ISSUE TITLE
How to remove ".exe" when calling commands

### ISSUE THREAD

**Issue by matinmn87** [dotnet/command-line-api#1742]
Hi. I have made a cli, but I want to call it in this way:
`mycli command --tag`
instead of this:
`C:/location/mycli.exe command --tag`
Is there a way to do that? Thanks

**Comment by elgonzo** [comment]
Yes. There is a way to do that. Howver, it is unrelated to System.CommandLine, and it is unrelated to any other bits of code in your program.

Rather, it is a function of the operating system you are using. Add the directory of your tool (not including the tool file name itself!) to the PATH environment variable. An overview how you could do that: https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them

**Comment by matinmn87** [comment]
> Yes. There is a way to do that. However, it is unrelated to System.CommandLine, and it is unrelated to any other bits of code in your program.
> 
> Rather, it is a function of the shell and/or operating system you are using. Add the directory of your tool (not including the tool file name itself!) to the PATH environment variable. An overview of how you could do that: https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them
> 
> (P.S.: Is your problem really with the .exe extension as your topic title suggests, or rather wanting to omit specifiying the path to your tool as your topic itself describes? I have to confess, i am a bit confused...)

Hello again. Both of them. no .exe, no path. I've searched for it, but I couldn't find the solution.
Thanks for your help

**Comment by elgonzo** [comment]
With respect to the directory path, the PATH environment variable will help you out with that. With respect to the .exe extension, i am afraid i don't fully understand. To execute an application with an .exe extensions from the prompt of the shell, the .exe extension is normally not required and calling your application without .exe extension should just work like that. Either you are not trying to call your application from a shell prompt as a assumed, or something else is borked with regard to the shell and environment you are using...

That said, if you can't come up with a workable solution by yourself, i would like to _strongly_ encourage you to move the question/discussion over to a site like [superuser.com](https://superuser.com/), which is specifically geared towards problems/questions of this nature.

I would also kindly request to close this issue here, unless you can make _clear_ that your problem is about some function or feature of the System.CommandLine library (remember, this here is the issue tracker for and about System.CommandLine). As it is presented now, your issue at hand is not related to System.CommandLine. System.CommandLine is a library that is (or can be) used by your application to consume CLI parameters, it is not a shell through which you start programs.

**Comment by matinmn87** [comment]
Ok. thank you
