### ISSUE TITLE
Beta 4: ArgumentArity.Zero required/missing

### ISSUE THREAD

**Issue by dorssel** [dotnet/command-line-api#1751]
Until Beta 4 I used `new Option(...)` for a "flag" option that could be present or not; simply tested for with `HasOption()`.

Since Beta 4 `Option` is abstract and requires an instantiation with a type, e.g. `new Option<bool>(...)`. This changes the parsing though! You can now still use it as a "flag" option : `--flag`, but also as `--flag=true` and (this is the confusing one): `--flag=false`. The last one makes it ambiguous if it is simply tested for with `HasOption()`. To avoid that, I have added `Arity = ArgumentArity.Zero`, so the option no longer allows any argument. This essentially brings back the no-argument "flag" option.

Problem is: `--help` was converted from `new Option()` to `new Option<bool>()` *without* `ArgumentArity.Zero`. So now you can invoke with `--help=false` without a parse error *and* you get help. This is confusing...

ADDED:
See https://github.com/dorssel/usbipd-win/pull/403/commits/3cc8e9d05c23726cbc80c935f68aea5bde6593d9#diff-82cc2bf60ada22c37fafd6f0c348d6f585fbac1e39c4df348a3507cf429239ceL151-L159

**Comment by jonsequitur** [comment]
`HelpOption` does have an arity of `ArgumentArity.None`: https://github.com/dotnet/command-line-api/blob/6c71bd788d9c8f8628787792d865b9eb683f851f/src/System.CommandLine/Help/HelpOption.cs#L35

I can see parse errors when parsing `--help=false`:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/547415/171929029-9c681483-de19-4702-8ca1-d348ddb837c1.png">

Using the `[parse]` directive you can see a bit more of what's happening: 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/547415/171929581-acbaaa4d-6302-464f-bc37-e155196eff93.png">

It's by design that we don't show parser errors when help has been requested. But maybe the design is wrong. For comparison, here's `git` versus the System.CommandLine-based help behavior (in `dotnet-interactive` which is on beta 4, though comparison with other tools shows the same behavior):

<img width="769" alt="image" src="https://user-images.githubusercontent.com/547415/171930661-24598d27-f31c-4f11-bb46-91090a672c47.png">

**Comment by dorssel** [comment]
@jonsequitur 
Oops ... I stand corrected.

I had just looked at the diff that made Option abstract: https://github.com/dotnet/command-line-api/pull/1677/files#diff-816b81f480c80c3ec23ba66b20c0605715b06805d412f13a4eaff7f9c0e6e7bcL6-R6.

I hadn't realized that Argument.None() was already in the HelpOption (and VersionOption) even before that. So when I changed my flag-options from `Option` to `Option<bool>` I had to add it, while for `--help` and `--version` this was in place all along.
