### ISSUE TITLE
Update to latest .Hosting beta forces ICommandHandler implementation change

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/command-line-api#1752]
2.0.0-beta4.22272.1

Must add this now - was that intended?

     public int Invoke(InvocationContext context) => throw new NotImplementedException();

**Comment by WeihanLi** [comment]
The same problem met

**Comment by jonsequitur** [comment]
Could you expand on the example?  What was the code you were using before and what do you need to do now?

**Comment by WeihanLi** [comment]
Hi @jonsequitur , since there's a new method `int Invoke(InvocationContext context)` added for `ICommandHandler` in beta4

![](https://user-images.githubusercontent.com/7604648/173277081-fae846e3-c8b3-4357-8b72-4401e95cdde5.png)


- <https://github.com/dotnet/command-line-api/compare/v2.0.0-beta3.22114.1...2.0.0-beta4.22272.1#diff-4225799b1e51b4a76969e695462201a528767f8d5c66948d59916a5029b68d98>
- <https://github.com/dotnet/command-line-api/compare/v2.0.0-beta3.22114.1...2.0.0-beta4.22272.1#diff-a36c7b11d9c1d0036406fa22d0442bb71aa978c06b273fa422eb187390d2b467>

when we upgrade the package from beat3 to beta4, had to implement this new method to fix the build error.

If it's really necessary to add it, maybe the default interface implement could help avoid breaking changes, maybe likes follows:

``` c#
public interface ICommandHandler
{
    int Invoke(InvocationContext context) => InvokeAsync(context).GetAwaiter().GetResult();
    // ...
}
```

**Comment by jonsequitur** [comment]
This is a great suggestion. We're not too concerned about breaking changes since we're still in beta, but this would also make it easier for people to do the right thing when implementing this interface.
