### ISSUE TITLE
How do you configure an Option<T> to behave like a switch (no arguments)?

### ISSUE THREAD

**Issue by aggieben** [dotnet/command-line-api#1764]
I'd like to set up a command that would take an option that carries no arguments with it.  Usage would be something like this:

```
mycli command --switch
```

I've tried setting up an option for `--switch` using an `Option<bool>` and it doesn't work as I'd expect it to.  I tried it like this:

```fsharp
let root = // ...blahblah, this part doesn't seem too relevant

let cmdHandler (host:IHost) (switch:bool) =
    printfn "handler called with switch: %A" switch

let cmd = Command("cmd")
let switch = Option<bool>("--switch")
cmd.AddOption(switch)
cmd.Handler <- CommandHandler.Create(cmdHandler)

root.AddCommand(cmd)
```

`cmdHandler` runs as expected when I invoke the command on the console, but `switch` is always false.  Is there a way to do this?

**Comment by baronfel** [comment]
what if you set the `Arity` property of the option to `ExactlyZero`?

**Comment by aggieben** [comment]
@baronfel In the latest nuget bits there is no `ArgumentArity.ExactlyZero`.  There is `ArgumentArity.Zero`,  and I have tried that as well, with no success.

**Comment by aggieben** [comment]
FWIW, another interesting behavior is that when I run the command and provide a boolean argument to `--switch`, it _still_ doesn't work as expected:

e.g., if I invoke `mycli command --switch true`, the `switch` parameter is still `false`.

**Comment by jonsequitur** [comment]
This looks like a binding issue. There are a lot of gotchas with using `CommandHandler.Create`, which uses name-based matching via reflection. I suspect the issue is an F#-specific wrinkle (because it looks like you've named the parameter correctly to satisfy the match.) 

We've been generally recommending that people use `Command.SetHandler` (introduced in beta 2) rather than `CommandHandler.Create`, as the API's behavior is clearer and it's more performant.

**Comment by aggieben** [comment]
Closing, given a recommendation away from this api.
