### ISSUE TITLE
[Feature Request] Use alternative console logger

### ISSUE THREAD

**Issue by lonix1** [dotnet/command-line-api#1844]
There are many places where we must specify strings which get logged, e.g. names and descriptions for commands / arguments / options, help texts, etc. In each case it may be possible to tweak the library to format the text in a certain way, but that's a lot of work.

It would be nice to have a global approach instead. I want to use "Spectre.Console" for *any loggable text anywhere in the system*.

For example:
````cs
public MyCommand() 
  : base("my-command", "this command writes the stuff to [b]stdout[/]")    // <----- notice
{
  //...
}
````
That `[b]...[/]` is probably hard to do right now. But if **every** loggable text went through the logger of my choice, I could just write log message however I want and know that my logger (Spectre.Console) would take care of it. I'd register it once in the `Program` class.

**Comment by jonsequitur** [comment]
This kind of thing was one of the long-term ambitions of the (now-deprecated) System.CommandLine.Rendering library. The markup would have to be handled by a formatter that is known to understand how to handle it, so generally wouldn't be passed out of proc, but VT codes were designed for just this kind of use. The problem is that there aren't standardized ways of asking command line tools for specific kinds of output, e.g. with or without VT codes. System.CommandLine's directives could potentially be used this way, like a sort of accept header for CLIs.
