### ISSUE TITLE
Retrieving extravagant/template-specific options? 

### ISSUE THREAD

**Issue by thinker227** [dotnet/command-line-api#1886]
I'm using the System.CommandLine options/arguments API, and I would like to do something like what `dotnet new <template>` does where it lists a set of options specific to the chosen template. I know the .NET CLI uses a custom fork of System.CommandLine, although I would still like to know if there's a decent way to pull off something similar using the existing System.CommandLine API.

**Comment by baronfel** [comment]
@thinker227 nothing custom at all, it's just using nightly builds of this repo :) `dotnet new` implemented its help output by almost entirely overriding the default layout, and it implements each template as a `Command` that is generated at runtime, instead of statically defined. So you could do the exact same thing today! @vlada-shubina do you have any specific pointers to places where we heavily customize the help output?

**Comment by thinker227** [comment]
That's very interesting, and yes I would love some additional pointers. I think I have an idea of how to do this now though, thanks.
