### ISSUE TITLE
Option binding issues with nested commands

### ISSUE THREAD

**Issue by deepchoudhery** [dotnet/command-line-api#2002]
Having issues with binding models or just straight arguments using the [documented method](https://learn.microsoft.com/en-us/dotnet/standard/commandline/model-binding).  Couple notes:
- System.Command version `2.0.0-beta4.22613.1`
- `BindingContext.ParseResult.GetValue` is coming up empty. GetValueForOption does not seem to exist in the version stated above.
- If not using the BinderBase method, the options are still binding individually in the SetHandler call.
- SetHandler calls [here](https://github.com/dotnet/Scaffolding/blob/e2c59f219066be20f6315761313c4eec64ebb122/tools/dotnet-msidentity/Program.cs#L66) and BinderBase inherited class [here](https://github.com/dotnet/Scaffolding/blob/dev/decho/bump-system-commandline/tools/dotnet-msidentity/ProvisioningToolOptionsBinder.cs).

**Comment by jonsequitur** [comment]
In your example, the methods that return your option objects are called multiple times but return a different instance each time:

```csharp
private static Option<bool> JsonOption =>
    new Option<bool>(
        aliases: new[] { "-j", "--json" },
        description: "Format output in JSON instead of text.\n")
    {
        IsRequired = false
    };
```

This means that the lookup for the option passed to the binder will not be using the same instance that was used to instantiate the parser, which is why the `GetValue` call comes up empty.

Changing the above method to a single-initialization property or field should fix this, e.g.:

```csharp
private static Option<bool> JsonOption { get; } =
    new Option<bool>(
        aliases: new[] { "-j", "--json" },
        description: "Format output in JSON instead of text.\n")
    {
        IsRequired = false
    };
```

**Comment by deepchoudhery** [comment]
oh okok cool, will try that. Ty

**Comment by deepchoudhery** [comment]
That worked, thanks. Closing
