### ISSUE TITLE
CancelOnProcessTermination no longer enabled by default

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#2111]
Before https://github.com/dotnet/command-line-api/pull/2044, the `CancellationToken` was hooked in the default configuration.

Now, you need to explicitly call `CancelOnProcessTermination`.

@adamsitnik is this an intentional change?

**Comment by adamsitnik** [comment]
It's a bug, it's going to be fixed with #2107

where the timeout is going to have 2s value by default and the users will need to set it to null to disable the feature.

https://github.com/dotnet/command-line-api/blob/2dd5b76efa1770ee230107e3d732fa9e03796e09/src/System.CommandLine/CommandLineConfiguration.cs#L76-L81
