### ISSUE TITLE
Invoking command via Parser doesn't write to console, whereas command.Invoke does

### ISSUE THREAD

**Issue by maccsek** [dotnet/command-line-api#2188]
I have a console application that uses `System.CommandLine` to parse arguments and options.

To be able to deal with exceptions better, I've switched from `RootCommand.Invoke(args)` to using a `CommandLineBuilder` in the way I saw discussed here in one of the earlier threads:
```
    CommandLineBuilder oCLB = new(oRootCmd);
    oCLB.UseExceptionHandler((e, c) => LogExceptionAndRaiseEvent(e));
    Parser oPrs = oCLB.Build();
    int iRC = oPrs.Invoke(p_StartupArgs);
```
Now I've noticed that this way of invoking doesn't write to the console anymore, neither when there is a parsing error nor when being called with the default help switch "-h".

I suspect it has to do with the second (IConsole) parameter in Invoke -- I've tried `oPrs.Invoke(p_StartupArgs, new SystemConsole());`, but without success. What am I missing?

**Comment by elgonzo** [comment]
If i am not mistaken, if you don't call _UseDefaults_ on your CommandLineBuilder you would need to call `UseParseErrorReporting` to configure the CommandLineBuilder for parse error output:

```C#
CommandLineBuilder oCLB = new(oRootCmd);
oCLB.UseParseErrorReporting();
oCLB.UseExceptionHandler((e, c) => LogExceptionAndRaiseEvent(e));
```
------
I do hesitate to recommend using _UseDefaults_ together with your own _UseExceptionHandler_ call. Because _UseDefaults_ also configures an exception handler. Therefore, calling both _UseDefaults_ and _UseExceptionHandler_ would result in two exception handlers being added to the CommandLineBuilder.

And there was a problem when adding multiple System.CommandLine middlewares with the same priority (such as multiple exception handlers). Due to a possibly unstable sorting algorithm used for sorting of the execution order of these middlewares, it would have been exceedingly difficult (i.e. practically impossible) to reliably predict which exception handler would be called first if multiple exception handlers were defined (such as would be the case when calling both _UseDefaults_ and _UseExceptionHandler_). Not sure if that sorting issue got fixed, but that seems to be a moot point to ponder anyways because:

Also worth of note, it seems CommandLineBuilder will be a thing of the past, being removed from the System.CommandLine library (see here: https://github.com/dotnet/command-line-api/pull/2107).

**Comment by maccsek** [comment]
Thank you, this was exactly what I needed! Works like a charm now, and I suppose when CommandLineBuilder gets deprecated, there'll be some other way of mixing my own exception handling with the regular help, version and parsing functionality.
