### ISSUE TITLE
Potential logic issue with CliSubsystem

### ISSUE THREAD

**Issue by JeanJoeris** [dotnet/command-line-api#2340]
Looking through the new Powderhouse code, I think there might be an issue with logic in the CliSubsystem I wanted to mention.

Specifically, looking at `TryGetAnnotation` within [CliSubsystem](https://github.com/dotnet/command-line-api/blob/main-powderhouse/src/System.CommandLine.Subsystems/Subsystems/CliSubsystem.cs#L43-L55) 
```csharp
protected internal bool TryGetAnnotation<TValue>(CliSymbol symbol, AnnotationId<TValue> id, [NotNullWhen(true)] out TValue? value)
{
    if (_defaultProvider is not null && _defaultProvider.TryGet(symbol, id, out value))
    {
        return true;
    }
    if (_annotationProvider is not null && _annotationProvider.TryGet(symbol, id, out value))
    {
        return true;
    }
    value = default;
    return false;
}
```

This method is set to prefer pulling the value from `_defaultProvider` over `_annotationProvider`. However, `SetAnnotation` defines `_defaultProvider`. So if `SetAnnotation` is called before `TryGetAnnotation` then `_annotationProvider` will never be called.

I suspect that we might want this in the other order (checking `_annotationProvider` before `_defaultProvider`) but there could be some subtle context I'm missing

**Comment by mhutch** [comment]
If `_defaultProvider` does not contain a value for the `symbol`+`id`, then `_defaultProvider.TryGet` will return `false`. This means the first `if` will evaluate as `false`.

The logic is as follows:

* If an annotation has been set for that `symbol`+`id` via `SetAnnotation`, it will be returned.
* Otherwise, if the `_annotationProvider` has been provided, it will be queried for the annotation.

**Comment by JeanJoeris** [comment]
Thanks for the context @mhutch

**Comment by JeanJoeris** [comment]
Gonna close this after clarifying 👍
