### ISSUE TITLE
Make StringExtensions a standalone class as opposed to an extension class

### ISSUE THREAD

**Issue by PonchoPowers** [dotnet/command-line-api#2436]
I can't see any benefit in making this a string extension, why not just create a class and pass the args into a method? In all cases I can think of, being an extension for a string is misleading, as this is specific to args, not strings.

**Comment by elgonzo** [comment]
Nothing forces you to use an extension method _only_ like an extension method. If you need or want, you can use an extension methods just like an ordinary static method.

That said, note that in the current (powderhouse branch) development of S.CL, the StringExtensions class has been made internal.

**Comment by elgonzo** [comment]
> [...]  which are infinitely useful for dealing with command lines, the use case at the moment seems too narrow minded as to parsing when the library could also be useful for generating commands too.

I am afraid don't follow you. What is useful about these methods in a way that you wouldn't be able to (relatively easily) achieve through one of the public methods provided by CliParser? "_generating commands_"... what exactly do you mean? Commands are generated by instantiating and setting up CliCommand instances.

> To put it into perspective, Tokenize should be split out into a class, and the CanBeUnbundled and TryUnbundle methods moved into the new class, but instead of nesting these methods, they should be separate so that they can be unit tested,

I tend to agree, but i fail to see how this is related to your OP that talked about some internal string-based extension methods preferably not being extension methods. I guess this should be a topic on its own instead of lumping it with this thread here turning it into a meandering discussion about this and that...

**Comment by elgonzo** [comment]
> Not sure if we are looking at the same code

Yes, we are. The source file is named StringExtensions.cs. However, the Tokenize method is in the Tokenizer class:
https://github.com/dotnet/command-line-api/blob/2946046fadd284ba7d2ed92e8bab68f5e5dac31f/src/System.CommandLine/Parsing/StringExtensions.cs#L32
