### ISSUE TITLE
Embedded quotes / json data as argument issue with examples

### ISSUE THREAD

**Issue by slee-accesso** [dotnet/command-line-api#2453]
Using C# .NET 8 on Windows 11 in PowerShell (5.1) I have this simple console program:

```csharp
using System.CommandLine;
namespace DemoIssue;
internal static class Program
{
    private static async Task<int> Main(string[] args)
    {
        var rootCommand = new RootCommand {Description = "This application is to demonstrate a parsing issue "};
        var postDataOption = new Option<string>("-data", "PostData");
        rootCommand.AddOption(postDataOption);
        rootCommand.SetHandler(postData => { Console.WriteLine($"PostData: {postData}"); }, postDataOption);
        return await rootCommand.InvokeAsync(args);
    }
}

```
By varying the placement of spaces in the json string, I can make it fail or succeed. If any embedded spaces are present, then at least one colon outside embedded quotes must have a space next to it (before or after). I also tried experiments with multiple colons. As long as one outside embedded quotes had a space, the rest seemed ok. 
```
>.\DemoIssue.exe -data '{\"myKey\":\"myValue\"}'
PostData: {"myKey":"myValue"}
>.\DemoIssue.exe -data '{\"myKey\": \"myValue\"}'
PostData: {"myKey": "myValue"}
>.\DemoIssue.exe -data '{\"myKey\": \"my Value\"}'
PostData: {"myKey": "my Value"}
>.\DemoIssue.exe -data '{\"my Key\": \"my Value\"}'
PostData: {"my Key": "my Value"}

>.\DemoIssue.exe [parse] -data '{\"my Key\": \"my Value\"}'
[ DemoIssue [ -data <{"my Key": "my Value"}> ] ]
```
These all fail:
```
>.\DemoIssue.exe -data '{\"myKey\":\"my Value\"}'
Unrecognized command or argument 'Value"}'.
>.\DemoIssue.exe -data '{\"my Key\":\"myValue\"}'
Unrecognized command or argument 'Key":"myValue"}'.
>.\DemoIssue.exe -data '{\"my Key\":\"my Value\"}'
Unrecognized command or argument 'Key":"my'.
Unrecognized command or argument 'Value"}'.

>.\DemoIssue.exe [parse] -data '{\"my Key\":\"my Value\"}'
![ DemoIssue [ -data <{"my> ] ]   ???--> Key":"my Value"}
>.\DemoIssue.exe [parse] -data '{\"myKey\":\"my Value\"}'
![ DemoIssue [ -data <{"myKey":"my> ] ]   ???--> Value"}
>.\DemoIssue.exe [parse] -data '{\"my Key\":\"myValue\"}'
![ DemoIssue [ -data <{"my> ] ]   ???--> Key":"myValue"}
```
Experiments with multiple colons. These work:
```
>.\DemoIssue.exe -data '{\"myKey\":\"my Value\",\"myKey2\": \"my:Value2\"}'
>.\DemoIssue.exe -data '{\"myKey\" :\"my Value\",\"myKey2\":\"my:Value2\"}'
```
These fail:
```
>.\DemoIssue.exe -data '{\"myKey\":\"my Value\",\"myKey2\":\"my:Value2\"}'
>.\DemoIssue.exe -data '{\"myKey\":\"my Value\",\"myKey2\":\"my :Value2\"}'
>.\DemoIssue.exe [parse] -data '{\"myKey\":\"my Value\",\"myKey2\":\"my :Value2\"}'
![ DemoIssue [ -data <{"myKey":"my> ] ]   ???--> Value","myKey2":"my :Value2"}
```
Is this going to be a case of "Me: Hey doc - it hurts when I do this ... " "Doc: Then stop doing that!"?

**Comment by elgonzo** [comment]
You should have checked the contents of the `args` array you pass to the library. Because, if the content in the `args` array is not "right", then there is nothing System.CommandLine can do about it.

Basically, in your situation it's the typical Powershell command-line argument quoting f**kery, mkay... 

For example, the command-line:
```
.\DemoIssue.exe -data '{\"myKey\":  \"myValue\"}'
```
will result in PS passing `-data "{\"myKey\":  \"myValue\"}"` to your app. Note the double quotes surrounding  the json argument.

However, with for example the command-line:
```
.\DemoIssue.exe -data '{\"myKey\":\"my Value\"}'
```
Powershell in its incomprehensible wisdom decides now **not** to use surrounding double quotes, passing `-data {\"myKey\":\"my Value\"}` to your app. Your app now basically sees three arg strings: `-data`, `{\"myKey\":\"my` and `Value\"}` Kaboom. It's Powershell, baby.


Side note: As you might have noticed, i am not a big fan of Powershell. I have given up long ago on PS precisely due to its byzantine command-line escaping/quoting rules, which work in mysterious ways and are far worse then ye'olde cmd.exe. Hence i am unfortunately also not able to advice of how to correctly escape/quote the command-line arguments in PS, because PS makes me angry. Try using double double-quotes `""` instead of escaped double-quotes `\"` and see what it gets you... ;-)

**Comment by slee-accesso** [comment]
Well, @elgonzo - if nothing else, you are hilarious : ) However I'm pretty sure System.CommandLine is not parsing correctly but PowerShell is. To test this, I made a PowerShell function that takes two string arguments so I could verify the parsing. I made two parameters to prove it took the first parameter (the json) as a single string, and still could see the second parameter. All of the test cases above parsed properly both as named and positional parameters. So - PowerShell can pass the string to PowerShell just fine - therefore, I think it is System.CommandLine's parser.

PowerShell test function:
```
function Reflect-Text ([Parameter()][String] $stringyString, [Parameter()][String] $secondString) {
    Write-Host "Reflection stringyString: $stringyString";
    Write-Host "Reflection secondString: $secondString";
}
```

Two sample calls/results - the first fails with System.CommandLine, the second passes but both work fine in PowerShell:
```
> Reflect-Text '{\"myKey\":\"my Value\",\"myKey2\":\"my:Value2\"}' 'Hello!'
Reflection stringyString: {\"myKey\":\"my Value\",\"myKey2\":\"my:Value2\"}
Reflection secondString: Hello!

> Reflect-Text '{\"myKey\":\"my Value\",\"myKey2\": \"my:Value2\"}' 'Hello again...'
Reflection stringyString: {\"myKey\":\"my Value\",\"myKey2\": \"my:Value2\"}
Reflection secondString: Hello again...
```

**Comment by slee-accesso** [comment]
Closing - as this isn't System.CommandLine : )

**Comment by elgonzo** [comment]
> They seem to have fixed the parsing sometime, apparently. PowerShell 7.4.3 does not screw it up. 

Oh, they did? Well, guess i have try it out, it seems ;-)
