### ISSUE TITLE
After changing a subcommand name, AliasedSet Contains doesn't find it

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/command-line-api#340]
To reproduce...

Create a command with subcommands (children via AddCommand)
`command.Children.Contains(<childname>)` is true
Change the Name property of a child
`command.Children.Contains(<newChildName>)` is false

You can confirm the names of the children in the watch window. 

It appears that the keys in the Aliased Set's HashSet do not respond to the mutation.

A few of the options:

- Figure out a way to update the AliasSet when the name changes. I do not see a way to accomplish this
- Not allow names to be changed at all
- Only allow names to be changed via a method on the AliasSet

**Comment by KathleenDollard** [comment]
Thinking more about this, we might consider a "freeze" of things when they are attached to other things. 

For me, I simply quit changing names, but we definitely want some guardrails here. 

I've worked around this, so this is not blocking me.

**Comment by jonsequitur** [comment]
The current intent is that:

1) `Command`, `Option`, and `Argument` are mutable prior to a `CommandLineConfiguration` being created, and 
2) the `CommandLineConfiguration`, which exposes a hierarchy of `ICommand`, `IOption`, and `IArgument`, should be immutable. 

On the mutable side, changing a name should be reflected in the API. If a reference to these instances was held and they're then mutated, the `CommandLineConfiguration` should not be affected.

This issue is definitely a bug in regards to point 1. 

We've discussed cloning objects in order to enforce point 2 but this hasn't been implemented yet.
