### ISSUE TITLE
Auto generated usage text doesn't mention mandatory argument

### ISSUE THREAD

**Issue by rchande** [dotnet/command-line-api#362]
I created a command like so:
```
Command thing()
            {
                var run = new Command("thing", "Try a thing", argument: new Argument<string>());

                run.Handler = CommandHandler.Create<string, IConsole>((string thing, IConsole console) =>
                {
                    if (string.IsNullOrEmpty(thing))
                    {
                        console.Out.WriteLine("nothing");
                    }
                    else
                    {
                        console.Out.WriteLine(thing);
                    }
                });

                return run;
            }
```

If I dotnet run my app without providing an argument, the output is:
```
Required argument missing for command: thing

thing:
  Try a thing

Usage:
  MLS.Agent thing
```

Note that the usage text doesn't actually mention the missing argument. I would have expected something like

```
MLS.Agent thing [arg]
```

**Comment by rchande** [comment]
cc @jonsequitur

**Comment by jeredm** [comment]
@rchande Can you please include the code for your Main method? I am not sure if this is a bug because the argument is not given a name. If you set the Name property when you instantiate the Argument object, help should display the name of the argument. I am asking for more info because my output looks different from yours and I am not sure if there is a change to help that is causing this difference. 

My help looks like this when I name the argument "hi":
```
Required command was not provided.

Usage:
  DotnetMetal [command]

Commands:
  thing <hi>    Try a thing
```

Here is the related code that makes me think the argument needs to be named:
https://github.com/dotnet/command-line-api/blob/5bace63365b71ce0c3001d50ec417e2201b37035/src/System.CommandLine/Help/Builders/HelpBuilder.cs#L449-L462

**Comment by jonsequitur** [comment]
I'm inclined to see this as a bug because it's confusing. The fact that there is an argument should be indicated in help even if it wasn't named.

That said, we might want to make argument names mandatory because they have a functional role in binding, which would solve this issue as well.
