### ISSUE TITLE
add benchmarks

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#469]
A small benchmark suite would be helpful so that we can measure work on performance improvements.

**Comment by Kosat** [comment]
Hello @jonsequitur ,

If I understand correctly, you would like to add a few __BenchmarkDotNet__ benchmarks into a new project , let it be `src/System.CommandLine.Benchmarks`. So that contributors would locally check their changes for performance degradation as explained [here](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-corefx.md#preventing-regressions).

Kindly, can I take this task?

**Comment by jonsequitur** [comment]
That approach sounds good. We'd absolutely appreciate the help.

Thanks @Kosat!

**Comment by billwert** [comment]
hey @jonsequitur - I think we should host these in the dotnet/performance repo as we do the [ml.net](https://github.com/dotnet/performance/tree/master/src/benchmarks/real-world/Microsoft.ML.Benchmarks). What do you think? That way we can run them often for you and you'll have trends (currently internal only, we're working on a reporting story for external.)

**Comment by billwert** [comment]
hi @Kosat! @jonsequitur and I chatteda about this yesterday. For now we think it is best to put the benchmarks in a place in this repo to enable highly iteratitve workflows for contributors here. Once we've reached some point of stability we'll look at putting this in the perf repo and lab to guard against regression.

If you're not familiar with it you might be able to use the [nuget support built into BDN](https://benchmarkdotnet.org/articles/samples/IntroNuGet.html). Wanted to call it out if you hadn't seen it.
