### ISSUE TITLE
CommandLine.ExecuteAssemblyAsync reference broken in generated Main()

### ISSUE THREAD

**Issue by clmcgrath** [dotnet/command-line-api#478]
After installing dragonfruit on a brand new project and adding a few parameters 
the AutoGeneratedProgram.g.cs breaks with a missing reference error  at CommandLine.ExecuteAssemblyAsync()
Currently targeting netcoreapp2.2

**Comment by jonsequitur** [comment]
Thanks. Could you provide more detailed repro steps and a code sample?

**Comment by clmcgrath** [comment]
i created i brand new project and it works now 
but in my template project it is breaking 
i will post a public repo for you

**Comment by clmcgrath** [comment]
https://github.com/DigitalParadox/DigitalParadoxCLI.Template/tree/develop

**Comment by clmcgrath** [comment]
It seems to be a conflict with commandlineparser after removing that package it seems to go away , and after reinstalling it it comes back

**Comment by Keboo** [comment]
@clmcgrath good catch on the namespace collision. I have submitted a PR to fix it. This fix wont completely fix your small sample project though. When using DragonFruit it expects that you will write a strongly typed Main method rather than a simple one with string arguments (`static async Task Main(string[] args)`). I suspect this is just an artifact of the sample project and not what you are actually doing in your actual CLI.

**Comment by clmcgrath** [comment]
correct ,  ya I just installed it again to regenerate the problem 
my actual use case has strongly typed args
