### ISSUE TITLE
System.CommandLine.DragonFruit and VisualBasic

### ISSUE THREAD

**Issue by DualBrain** [dotnet/command-line-api#492]
When I create a new console project (.NET Core) for VB and add via nuget System.CommandLine.DragonFruit; when attempting to build I get the following error.  

Severity	Code	Description	Project	File	Line	Suppression State
Error	BC2014	the value '7.1' is invalid for option 'langversion'	ConsoleApp_DragonFruit	D:\GitHub\System_CommandLine_DragonFruit_VB\ConsoleApp_DragonFruit\vbc	1	Active

No other changes have occured with the default project other than adding System.CommandLine.DragonFruit from nuget.

Thoughts?

Thanks.

**Comment by Keboo** [comment]
@DualBrain not sure on the error, but currently the DragonFruit project is [currently setup to generate a C# entry point](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine.DragonFruit/targets/System.CommandLine.DragonFruit.targets#L22-L47) which would end up failing. 

I suspect the error you are seeing is being caused because it [tries to add some MSBuild properties](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine.DragonFruit/targets/System.CommandLine.DragonFruit.targets#L10) that the VB project does not support (this is a bit of a guess).

**Comment by amis92** [comment]
Judging by the error it's actually because LangVersion-setting property group doesn't have a Condition on Language being C#: https://github.com/dotnet/command-line-api/blob/b34be6226baaf6057b81da336e280b9b6dbf6b11/src/System.CommandLine.DragonFruit/targets/System.CommandLine.DragonFruit.targets#L7-L11

And well, there is no VB v7.1
