### ISSUE TITLE
DragonFruit appears broken in 19174.3

### ISSUE THREAD

**Issue by shueybubbles** [dotnet/command-line-api#521]
I tried upgrading from 19156.3 to 19174.3 today but my app wouldn't run with any valid command line args.
My main prototype:

`private static async Task Main(string source = null, 
            string destination = null, 
            string resultsFolder = null,
            Comparison[] comparison = null,
            string collectionSource = null,
            string collectionFolder = null)`

This works fine on 19156.3

E:\src\mssqltools\ssms\src\DbDiff\ConsoleHost>dotnet run @f:\temp\test.rsp
Unrecognized command or argument '--collection-source redacted'
Unrecognized command or argument '--collection-folder f:\temp\source'
Unrecognized command or argument '--comparison Configuration'

DbDiff:
  Compares two database instances to determine if query plans are likely to change between them

Usage:
  DbDiff [options]

Options:
  --source <SOURCE>                          Connection string of the source database, or the path to a folder where a previous collection was saved
  --destination <DESTINATION>                Connection string of the destination database, or the path to a folder where a previous collection was saved
  --results-folder <RESULTS-FOLDER>          Optional folder to persist a detailed results report
  --comparison <COMPARISON>                  Optional identifier of a type of comparison or collection to run. Include multiples using a switch per entry. Choices are: Schema, Statistics
  --collection-source <COLLECTION-SOURCE>    Connection string of the database for which data will be collected for offline comparison.
  --collection-folder <COLLECTION-FOLDER>
  --version                                  Display version information

**Comment by jonsequitur** [comment]
Thanks, David. Could you provide the contents (or a reasonable facsimile) of the response file?

**Comment by shueybubbles** [comment]
I see the same error passing the args on the command line as in the response file
In the rsp each arg has its own line

--collection-source Data Source=ssmsv12tests.database.windows.net;Initial Catalog=keep_WideWorldImporters;User Id=fakeid;Password=fakepwd
--collection-folder f:\temp\source
--comparison Configuration

**Comment by Keboo** [comment]
I was not able to reproduce the problem on the command line, however I did see similar behavior with response files. I also did not check the old version to see exactly which change caused the difference in behavior.
I believe the issue is the default handling of the response files. [By default](https://github.com/dotnet/command-line-api/blob/6d244f5de41c39724a80793633416587dbb51cd4/src/System.CommandLine/CommandLineConfiguration.cs#L24) it breaks apart the lines in the response file as though each piece was an individual token ([example unit test](https://github.com/dotnet/command-line-api/blob/4c2c852af940d17e5b07b5291e127bdb56cc02f2/src/System.CommandLine.Tests/ResponseFileTests.cs#L51-L69)). 
So for your response file I believe you want it to be:
```
--collection-source 
Data Source=ssmsv12tests.database.windows.net;Initial Catalog=keep_WideWorldImporters;User Id=fakeid;Password=fakepwd
--collection-folder 
f:\temp\source
--comparison 
Configuration
```

**Comment by shueybubbles** [comment]
the rsp processing must have changed between 19156.3 and the new version, as trying to put the argument on the line after the switch leads to an error on 19156.3. 
I will upgrade again when I have a chance and close this issue once I've adapted.

**Comment by jonsequitur** [comment]
Looking at @Keboo's comment and the behavior change here, I think the behavior was incorrect before.
