### ISSUE TITLE
ZeroOrMore options conflicts with ZeroOrMore arguments

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/command-line-api#527]
I have a small repro where I have both an option of ZeroOrMore arity and an argument of ZeroOrMore arity. It seems to me that the parsing doesn't give the corret results. The repro can be found at https://github.com/JunTaoLuo/ToolRepro. 

Input:
```
--opts opt1 arg1
```

Expected Output:
```
Opts:
opt1
Args:
arg1
```

Actual Output:
```
Opts:
opt1
arg1
Args:
```

If no options is specified, i.e. no `--opts opt1`, arg1 is parsed correctly.

Is this a known limitation or a bug?

cc @jonsequitur

**Comment by jonsequitur** [comment]
This is by design. Since parsing is greedy, the syntax you've set up here requires either that you put the arguments before the options on the command line, e.g.

```console
> myapp arg1 arg2 arg2 --opts opt1 opt2 opt3
```

or that you specify an upper bound on the arity of the option.

Previously this wasn't an issue because we forced re-specification of the options:

```console
> myapp --opt2 opt1 --opts opt2 arg1
```

This requirement was relaxed in order to resolve https://github.com/dotnet/command-line-api/issues/383.

Another possible resolution is to differentiate your arguments by target type rather than using `string`
 for both, though this may not always work.

**Comment by JunTaoLuo** [comment]
I see, we'll re-evaluate our design. Thanks.
