### ISSUE TITLE
Implementing suggestions undocumented

### ISSUE THREAD

**Issue by cmeyertons** [dotnet/command-line-api#650]
In the `Features -> Suggestions` gif, it looks like suggestions are enabled for a subset of arguments as the gif tabs through `--format Summary` then `--format Json`

is there a code example for enabling auto-complete for Summary -> Json?

**Comment by jonsequitur** [comment]
The code to configure the option is here: https://github.com/jonsequitur/t-rex/blob/3d41d8475c6094a3519d1aac1f6bb7d5e7b476b9/t-rex/CommandLine.cs#L28-L30

Because the argument is `new Argument<OutputFormat>(OutputFormat.Summary))`, and `OutputFormat` is an enum, the autocomplete functionality defaults to using the values in the enum.
