### ISSUE TITLE
Providing custom validation messages using CommandLineBuilder

### ISSUE THREAD

**Issue by sywhang** [dotnet/command-line-api#653]
Is there a way to provide a custom validation message using `CommandLineBuilder`? From what I can see, there is a ValidationMessages.Instance that gets passed directly in the constructor of `Parser` and neither of `CommandLineConfiguration` property inside `Parser` or `ValidationMessages` property inside `CommandLineConfiguration` is setable. 

If this is not possible, is there a way to create a `Parser` using `CommandLineBuilder` with my own instance of `CommandLineConfiguration`?

**Comment by jonsequitur** [comment]
It would be straightforward to add this functionality to `CommandLineBuilder`. 

In the meantime, you could create a `CommandLineConfiguration` directly, passing the `ValidationMessages` instance to its constructor. (`CommandLineBuilder` exists to help you compose arguments for the `CommandLineConfiguration` constructor, since `CommandLineConfiguration` is effectively immutable but has a somewhat complex constructor.)

**Comment by mikelle-rogers** [comment]
@jonsequitur, was this issue fixed, or just closed? If it still needs to be fixed, I would be interested in learning about it.
