### ISSUE TITLE
Multiple flag options

### ISSUE THREAD

**Issue by Alxandr** [dotnet/command-line-api#669]
How do you create something that can parse `-vvv` or `--verbose --verbose --verbose`? The way to make an option take multiple values is by having it accept an array, but in this case, there is no values provided.

**Comment by jonsequitur** [comment]
Would you expect this to bind to, for example, an array of `bool`?

**Comment by Alxandr** [comment]
More like an int to be honest. I think this may warrant a new type with just a count property. Bool array can be passed false after all. In other frameworks I've worked with, this is treated as a option of type count, as opposed to flag or value.

**Comment by jonsequitur** [comment]
Can you describe a use case?

**Comment by Alxandr** [comment]
It's quite common to have unix programs that allow you to increase verbosity with `-v`, and reduce it with `-q`. Take this pseudo-code for instance:

```csharp
var verbosity = Verbosity.Warning;
var verboseOption = new Option(new[] { "--verbose", "-v" }) { Argument = CountOccurencesArgument /* pseudo api */ };
var quietOption = new Option(new[] { "--quiet", "-q" })  { Argument = CountOccurencesArgument /* pseudo api */ }

// add validation that verbose and quiet can not be used both at the same time.
command.Add(verboseOption);
command.Add(quietOption);
var parsed = command.Parse(args);

if (command.HasOption(verboseOption)) {
  // pretend we get count here.
  int verboseOccurences = command.GetOptionValue(verboseOption);
  verbosity += verboseOccurences;
} else if (command.HasOption(quietOption)) {
  // pretend we get count here.
  int quietOccurences = command.GetOptionValue(quietOption);
  verbosity -= verboseOccurences;
}

ConfigureLogging(verbosity);
```

**Comment by giggio** [comment]
I solved this in a very ugly way, but it works. It has some rough edges, but it is enough for me right now. 

This is the workaround I found. This is all in a model binder class.

`VerboseOption` is a field, it is defined as:

```csharp
VerboseOption = new Option<bool>(aliases: new[] { "-v", "-vv", "--verbose" }, description: "Show verbose output.");
```
This is in `GetBoundValue` in model binding:

```csharp
var tokens = bindingContext.ParseResult.Tokens;
var matchedTokens = tokens.Select(token => token.Value).Where(token => VerboseOption.Aliases.Any(alias => alias == token)).ToList();
var verbosity = matchedTokens.Count switch
{
    0 => Verbosity.Quiet,
    1 => matchedTokens.Any(token => token == "-vv") ? Verbosity.VeryVerbose : Verbosity.Verbose,
    _ => Verbosity.VeryVerbose,
};
return new(verbosity);
```

This is error prone because I'm taking the tokens that are showing in `bindingContext.ParseResult.Tokens` and hoping they are the same symbols as the ones defined in my option. They could mean something else, but as their name is very explicit the chance is small.

I wish this library had a better solution for this problem.
