### ISSUE TITLE
CommandExtensions.Parse returns ParseResult with an Error for the --help argument

### ISSUE THREAD

**Issue by brandonschmidt** [dotnet/command-line-api#691]
Not sure if this is by design or not, but CommandExtensions.Parse will treat --help (and it's variations) as an invalid argument even though that's part of the built-in, default help feature.

The code below is copied from [Your first app with System.CommandLine](https://github.com/dotnet/command-line-api/wiki/Your-first-app-with-System.CommandLine) and returns the following error message (`Unrecognized command or argument '-h'.`).  And it will also return the default help text.  

```C#
static int Main(string[] args)
{
    // Setup test scenario: Pass a help argument.
    args = new[] { "-h" };

    // Create a root command with some options
    var rootCommand = new RootCommand
    {
        new Option(
            "--int-option",
            "An option whose argument is parsed as an int")
        {
            Argument = new Argument<int>(defaultValue: () => 42)
        },
        new Option(
            "--bool-option",
            "An option whose argument is parsed as a bool")
        {
            Argument = new Argument<bool>()
        },
        new Option(
            "--file-option",
            "An option whose argument is parsed as a FileInfo")
        {
            Argument = new Argument<FileInfo>()
        }
    };

    rootCommand.Description = "My sample app";

    rootCommand.Handler = CommandHandler.Create<int, bool, FileInfo, bool>((intOption, boolOption, fileOption, help) =>
    {
        Console.WriteLine($"The value for --int-option is: {intOption}");
        Console.WriteLine($"The value for --bool-option is: {boolOption}");
        Console.WriteLine($"The value for --file-option is: {fileOption?.FullName ?? "null"}");
    });

    // START - New code to check for parsing errors.
    var result = rootCommand.Parse(args);
    if (result.Errors.Count > 0)
    {
        Console.WriteLine($"{ result.CommandResult.ErrorMessage}");  // This returns: null

        foreach (var e in result.Errors)
            Console.WriteLine($"{e.Message}.");  // This returns: Unrecognized command or argument '-h'.
    }
    // END - New code to check for parsing errors.

    // Parse the incoming args and invoke the handler
    return rootCommand.InvokeAsync(args).Result;
}
```

I am using the following:
0.3.0-alpha.19573.2
.NET Core 3.0
Any CPU

**Comment by jonsequitur** [comment]
I would say this is a bug because it's surprising and unintuitive. I'll explain the reason this happens, but also I think we should fix it.

The parse errors result from the implementation of the help option. It's implemented as a middleware component and not as an `Option` so it doesn't really exist in the parser configuration. This results in the parse error if you explicitly check `ParseResult.Errors`. But the middleware doesn't care about that and short circuits to display help before checking for a parse error.

The advantage to this approach is that it allows `-h`, `/?`, and so on to act like a command rather than an option, especially since it's applied to every subcommand, so that the following are all valid:

```console
> myapp -h
> myapp subcommand -h
> myapp sub-subcommand -h #etc
```

But I think we could implement this as a proper `Option`, which would fix this bug, make things more consistent, and allow `-h` itself to appear in help output, which it current does not (#506).
