### ISSUE TITLE
Argument<T> constructor shouldn't accept a null default value func

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/command-line-api#728]
This was a simple gotcha that took a bit too long to sort out:

```
var option = new Option("--log", "file to write a log to") { Argument = new Argument<string?>(defaultValue: null).LegalFilePathsOnly() }
```

defaultValue is a parameter not of type `string?` but `Func<string?>`, so passing null meant the default argument didn't actually exist, but the library would internally null ref when trying to use that func. Compare to this:

```
var option = new Option("--log", "file to write a log to") { Argument = new Argument<string?>(defaultValue: () => null).LegalFilePathsOnly() }
```

which is correct!

It seems a null check should be added to here:

https://github.com/dotnet/command-line-api/blob/5c16ca9f61fe45275614fa52f561c833d0943178/src/System.CommandLine/Argument%7BT%7D.cs#L23

to prevent defaultValue from being null. Also, if this constructor was null annotated with C# 8.0 nullable annotations this could have been caught statically.

**Comment by jonsequitur** [comment]
Let me know what you think of the fix. Note that the `Argument.SetDefaultValue(Func<object>)` overload is still allowed to return null. This turns out to be important because the API is meant to enable creating your own conventions. One example, in DragonFruit, configures the parser based on method signatures, e.g. `MyMethod(string value = null)`. This infers the arity of the argument (minimum 0, maximum 1) and reflects that its default is in fact `null`. 

Any suggestions for improving the API are welcome.

> Also, if this constructor was null annotated with C# 8.0 nullable annotations this could have been caught statically.

Similarly, this might be a little tricky for the cases where the configuration is being done based on reflection. This could argue for distinct generic (null-annotated) versus non-generic (non-null-annotated) methods.

**Comment by jasonmalinowski** [comment]
@jonsequitur: yep, it totally makes sense that the default value can be null. It's just that the default value _factory_ itself really shouldn't be null because that implies you don't actually have a default value. The PR implied that you were blocking both though so that was a bit unclear.

Honestly the other confusion of this API that keeps throwing me is that the parameter is called "defaultValue" for both something that actually takes the value, and for something that is the factory.
