### ISSUE TITLE
Enable capturing unbound arguments.

### ISSUE THREAD

**Issue by redoz** [dotnet/command-line-api#789]
Say I generate a set of options/arguments from some data, I would like to be able to explicitly specify the arguments I know about, and capture the result from the rest in some generic collection object as the "Rest" parameter.

`foo.exe --foo 3 --bar x --g1 z1 --g2 z2`

`Task<int> Handler(int foo, string bar, UnboundArguments rest) {...}` where `rest` contains the parse results of `--g1 z1 --g2 z2`

**Comment by redoz** [comment]
Apparently possible by adding `ParseResult` as a parameter.

**Comment by jonsequitur** [comment]
`ParseResult.UnmatchedTokens` will give you the tokens but they're treated by default as errors. If you don't want them treated as errors, you can set this per command:

```csharp
> command.TreatUnmatchedTokensAsErrors = true;
```

One thing to note is that because the tokens only carry the string values, if you also want them converted for you, could alternatively capture them using an argument, e.g.:

```csharp
var cmd = new RootCommand
{
    new Argument<FileInfo[]>()
};
```

**Comment by redoz** [comment]
@jonsequitur 
I ended up doing something like
```csharp
var optionResult = parseResult.FindResultFor(option);
if (optionResult is object) {
  var values = optionResult.GetValueOrDefault<List<string>>();
  ...
}
```
Which worked our very nice, the trick was adding the ParseResult as an argument for my command handler.
