### ISSUE TITLE
How to configure this so parsing works as expected?

### ISSUE THREAD

**Issue by taori** [dotnet/command-line-api#830]
var testCommand = new Command("test");
	testCommand.AddArgument(new Argument<string>("-a") { Arity = ArgumentArity.ExactlyOne });
	testCommand.AddArgument(new Argument<string>("-b") { Arity = ArgumentArity.ExactlyOne });

![grafik](https://user-images.githubusercontent.com/5545184/77424291-27b53180-6dd1-11ea-97fb-2e6e9dcfe3a8.png)

This does not behave the way i would expect it to.

**Comment by taori** [comment]
if i use options instead i can switch parameter order. is that working as intended?

**Comment by jonsequitur** [comment]
Yes. To explain in more detail: argument names are used only for binding. Option names are syntactical. So given your code above, this would be a valid call:

```console
> test "parameter a" "parameter b"
```

The extra tokens are considered errors because `-b` and `"parameter b"` are being parsed as the values of the arguments. The rest are unrecognized tokens.

And yes, argument order is significant relative to other arguments, whereas options can occur in any order. So when you make them options, either of the following is equivalent:

```console
> test -a "parameter a" -b "parameter b"
> test -b "parameter b" -a "parameter a"
```

One other note, you shouldn't have to set the arity in the vast majority of cases, as it's inferred from the `Argument<T>` or `Option<T>` generic parameter type.

Hope that helps.
