### ISSUE TITLE
Return Different Result Code for -h / --help

### ISSUE THREAD

**Issue by markolbert** [dotnet/command-line-api#850]
I think the Invoke() methods should return a different result when -h (or any other short-circuiting flag) is specified.

The current approach, which returns a success code (0), isn't unreasonable since -h is a valid command line argument. But it's a different kind of valid command line argument since it, by default, automatically displays help text (and short-circuits binding, as I recall).

So I'd like to see it return a different result code. Failing that, is there a way to add a property to Command to indicate a short-circuit occurred?

**Comment by jonsequitur** [comment]
Is the goal to know that the invocation chain was short-circuited (i.e. a signal to people writing code with System.CommandLine) or to tell users of tools built with System.CommandLine that help was requested?

**Comment by markolbert** [comment]
Good question. Probably the former but I could see the case for each. What do you see as driving the need for the latter?

**Comment by jonsequitur** [comment]
One of the goals of middleware is to provide cross-cutting functionality, so the less that any middleware component depends on the behavior of other middleware, the more robust it's likely to be.

As for the result code, this is interesting because a number of command line tools return non-zero results when help is requested, though I'm not familiar with the use cases. A sampling:

A quick survey:

| Tool                        |  Result code for help |
| --------------------------- |:---------------------:|
| dir                         | 0
| dotnet                      | 0
| git                         | 129
| node                        | 0
| npm                         | 1

**Comment by ffes** [comment]
In the case of `git` it is because of different behavior. `git -h` gives you a short list of the command line options generated by the executable itself. `git --help` opens the man page.

This works the same for all the subcommands of git. Try for instance `git commit -h`  vs `git commit --help`.
