### ISSUE TITLE
Command with multiple args and option. Possible incorrect parse of arguments

### ISSUE THREAD

**Issue by narcis-pv** [dotnet/command-line-api#886]
Given the following command line args: `ConnectionString ApplicationName NotSet C:\ "D:\Source" --filter=test` with setup:
```
 new Command("ConnectionString")
                {
                    new Command("ApplicationName")
                        {
                            new Argument<AppNameStyle>("style")
                            {
                                Arity = ArgumentArity.ExactlyOne
                            },

                            new Argument<FileSystemInfo>("paths")
                            {
                                Arity = ArgumentArity.OneOrMore,
                            }.ExistingOnly(),

                            new Option(new[] {"--filter", "-f"})
                            {
                               // Note: Without this, the filter option argument is treated as argument of the command
                               // Argument = new Argument<string> {Arity = ArgumentArity.ExactlyOne}
                            },
                          // ...
```
If the last of option does not specify an argument, although I pass it as an option argument via `--filter:test`, then `test` value is considered to be a command argument.

This really took me by surprise. IHMO the moment an option is encountered, any previous arguments with arity "more" should be considered finished.

This feature was introduced as part of #310

**Comment by jonsequitur** [comment]
The reason adding the argument changes the parsing behavior is the implicit arity. (`Option<string>` is a more concise way to do the same thing). Setting the type implicitly sets the arity, in this case to `ArgumentArity.ExactlyOne`. For your `--filter` option (declared as `Option` rather than `Option<T>`) you haven't set an arity or an `Argument.ArgumentType` that could be used to infer the arity, so it defaults to `ArgumentArity.Zero`.

On a related note, instead of this:

```csharp 
new Argument<FileSystemInfo>("paths")
{
    Arity = ArgumentArity.OneOrMore,
}
```

you can do this: 

```csharp
new Argument<FileSystemInfo[]>("paths")
```

The inferred arity for command arguments that are sequence types (lists, arrays, etc.) is `ArgumentArity.OneOrMore`, so it's not necessary to specify the arity, and the sequence type will be bound correctly.
