### ISSUE TITLE
Multi-level complex object binding

### ISSUE THREAD

**Issue by diredev** [dotnet/command-line-api#896]
Using complex object binding I am able to pass in an object holding other options. I then tried adding a property holding another complex object, essentially creating a tree of options: 

```csharp
class ComplexArgument
{
    public string Name { get; set; } // Mapped to --name
    public int Age { get; set; } // Mapped to --age

    // Complex child property
    public ComplexArgumentSub Sub { get; set; }
}

class ComplexArgumentSub
{
    public string Description { get; set; } // Mapped to --description
}
```

The idea is that this would allow to neatly group related options and reduce the number of properties on the top-level object.

This does not work as expected however, the complex property will always remain `null`.

Is there a way to achieve this using `System.CommandLine`?

----

Note that I've used a basic command configuration:

```csharp
static void Main(string[] args)
{
    var builder = new CommandLineBuilder().UseDebugDirective().UseExceptionHandler();

    var command = new Command("cmd")
    {
        new Option<string>("--name"),
        new Option<int>("--age"),
        new Option<string>("--description")
    };
    command.Handler = CommandHandler.Create<ComplexArgument>(Run);
    builder.AddCommand(command);

    builder.Build().Invoke(args);
}

static void Run(ComplexArgument arg)
{
    Console.Out.WriteLine("{0}, {1}: {2}", arg.Name, arg.Age, arg.Sub?.Description);
}
```

**Comment by jonsequitur** [comment]
The binding conventions don't currently support this because as you deepen the graph, it becomes harder to reason about and the code necessarily becomes more complex and slower. This isn't to say this can't be done, but this is why we haven't tried to tackle it.

Consider a couple of cases:

Ambiguity:

```csharp
public class One
{
    public Two Two { get; set; }
    public Three Three { get; set; }
}

public class Two
{
    public string Value { get; set; }
}
public class Three
{
    public string Value { get; set; }
}
```

Recursion:

```csharp
public class Node
{
    public Node Next { get; set; }
}
```

You can currently bind graphs using a custom `ParseArgument<T>` delegate, and there's [work underway](https://github.com/KathleenDollard/command-line-api-starfruit) on supporting more complex conventions.

**Comment by diredev** [comment]
Thank you for your feedback.
I'd consider the option-collision and recursion cases to be invalid (i.e. cause Exceptions).

I'll make sure to check the new conventions you'll come up with. 👍
