### ISSUE TITLE
Is there any way to create a Single binary conglomerate CLI tool like the realization of BusyBox?

### ISSUE THREAD

**Issue by LokiSharp** [dotnet/command-line-api#900]
Hi there. as the title say, I'm finding a way to write a Single binary CLI tool like the realization of Busybox. As Reads `argv[0]` to find the name by which it is called, and runs the appropriate command

When I try to do it, I find a problem. With .Net Core Runtime not only args for `Main()` but also `Environment.GetCommandLineArgs()` doesn't include the real name of the program passed to the runtime as first argument like C/C++. .Net Core Runtime's executable file doesn't passed the real name of the program to the runtime. It only passed the path of dll.

BusyBox is a single binary program. Each command can accessed by calling symbolic link whick linked to busybox binary with the corresponding command name.

Example from Wikipedia(https://en.wikipedia.org/wiki/BusyBox#Examples)
>Programs included in BusyBox can be run simply by adding their name as an argument to the BusyBox executable:
>
>`/bin/busybox ls`
>
>More commonly, the desired command names are linked (using hard or symbolic links) to the BusyBox executable; BusyBox reads `argv[0]` to find the name by which it is called, and runs the appropriate command, for example just
>
>`/bin/ls`
>
>After /bin/ls is linked to /bin/busybox. This works because the first argument passed to a program is the name used for the program call, in this case the argument would be "/bin/ls". Busybox would see that its "name" is "ls" and act like the "ls" program.

**Comment by jonsequitur** [comment]
This could potentially be made to work. It's not something I've looked into. I can offer some clues and would love to hear people's thoughts.

There are some related pieces of code in the parser that were added to rationalize "`argv[0]`", for example when it's passed by a script (including completion scripts) or when we're parsing complete command line strings rather than the pre-split `Main` arguments.

This code normalizes the root command: 

https://github.com/dotnet/command-line-api/blob/011b81c62e18b3cd139425b6cba18edbf41f9222/src/System.CommandLine/Parsing/StringExtensions.cs#L319

This code figures out the root command's name (but is irrelevant when an alias is used):

https://github.com/dotnet/command-line-api/blob/5ec6c4a5e1a0162d0dc7ef9527e0c2083cc0fd87/src/System.CommandLine/RootCommand.cs#L36-L49

**Comment by LokiSharp** [comment]
Thank for your reply. I find this code in Test Utility could use a native API to get the real argv, but seems like an unoffical trick. Is that possable merge to RootCommand.

https://github.com/dotnet/command-line-api/blob/750fdd13142091b7407c9c8a68c22012a095d183/src/System.CommandLine.Tests/Utility/RemoteExecutor.cs#L150-L176

**Comment by jonsequitur** [comment]
Possibly, yes. Do you know if this gets an alias/simlink name if that was used in the invocation? I'd also want to verify that the behavior is consistent and robust across different operating systems.

**Comment by LokiSharp** [comment]
I think most of common linux distribution has same  procfs at /proc. But some uncommon distribution like embedded Linux maybe remove procfs to save space. And OSX or other Unix doesn't have procfs by default too.

https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe
