### ISSUE TITLE
Using option (Arity.ZeroOrMore) with subsequent argument causes error

### ISSUE THREAD

**Issue by Apollo3zehn** [dotnet/command-line-api#910]
I have the following setup:

```cs
using System.CommandLine;
using System.Threading.Tasks;

namespace logs
{
    class Program
    {
        static async Task<int> Main(string[] args)
        {
            var command = new Command("exec")
            {
                new Option(new string[] { "--arg", "-a" })
                {
                    Argument = new Argument<string[]>()
                }
            };

            command.AddArgument(new Argument<string>("script-path"));

            var rootCommand = new RootCommand("MyRootCommand");
            rootCommand.AddCommand(command);

            return await rootCommand.InvokeAsync(args);
        }
    }
}
```

When I call this app with the arguments `exec --arg value1 --arg value2 script.ps1` I get the error `Required argument missing for command: exec`.

This is because the parser thinks my "script.ps1" belongs to the `--arg` option and then it complaints that there is to argument provided.

Do I use this the wrong way or is this an error? Is there any workaround? Thanks!

**Comment by jonsequitur** [comment]
There are a couple of ways this can work. If you can differentiate the arguments by type, the parser will move on if it can't convert, so for example if `--arg`'s argument were `Argument<int>` then it should work. Custom validators will accomplish this same thing but of course this depends on being able to differentiate them by target type at parse time based on the inputs, which in your example clearly won't work. 

This could work but won't entirely eliminate the possibility of an ambiguity:

```csharp
command.AddArgument(
  new Argument<FileInfo>("script-path").ExistingOnly());
```

Failing those, another thing that will work here (but it's not great because it falls to the end user to know how to do this) would be to put the command argument before the options:

```console
> exec script.ps1 --arg value1 --arg value2 
```

@KathleenDollard @Keboo Other ideas?

**Comment by Apollo3zehn** [comment]
Thansk for your suggestestions, but replacing `string` with `FileInfo` does not work:

```cs
var command = new Command("exec")
{
    new Option(new string[] { "--arg", "-a" })
    {
        // int instead of string (but I need string)
        Argument = new Argument<int[]>()
    }
};

// file info instead of string
command.AddArgument(new Argument<FileInfo>("script-path").ExistingOnly());

var rootCommand = new RootCommand("MyRootCommand");
rootCommand.AddCommand(command);

return await rootCommand.InvokeAsync(args);
```
Called with `exec --arg 1 --arg 2 script.ps1`. The result is again `Required argument missing for command: exec`.

Only `exec script.ps1 --arg 1 --arg 2` works.
