### ISSUE TITLE
[Question] Output simple exception message with red color text

### ISSUE THREAD

**Issue by shaggygi** [dotnet/command-line-api#921]
Trying to figure out how to display simple exception messages with red color similar to how the CLI does for invalid commands/options. I may be overlooking, but couldn't find examples in the wiki.  Currently an exception will show entire exception trace/info.

Any help is appreciated.

**Comment by jonsequitur** [comment]
If you're using `CommandLineBuilder.UseExceptionHandler`, `RootCommand.Invoke`, or DragonFruit, you see the default behavior implemented here:

https://github.com/dotnet/command-line-api/blob/750fdd13142091b7407c9c8a68c22012a095d183/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L246-L276

It sounds like this is the case since you're seeing a stack trace. If it's not red, it's possibly terminal-specific. If you're just wanting to change the error message, you can call `UseExceptionHandler` with a custom `onException` argument.

Let me know if that helps.

**Comment by shaggygi** [comment]
@jonsequitur 
The `UseExceptionHandler` was what I needed.  It looks like the color methods you referenced (e.g. [ResetTerminalForegroundColor](https://github.com/dotnet/command-line-api/blob/08362e7a1136586f5f91e7375fc12312454b35dd/src/System.CommandLine/IO/ConsoleExtensions.cs#L28), etc.) are internal as I couldn't see, so I had to do the following:

```csharp
private static void CvipbExceptionHandler(Exception exception, InvocationContext context)
{
    Console.ForegroundColor = ConsoleColor.Red;
    context.Console.Error.WriteLine(exception.InnerException.Message);
    Console.ResetColor();
}
```

As usual, thanks for the help!

**Comment by jonsequitur** [comment]
You're welcome.

The reason those methods are internal is because we're working on a generalization that will work for virtual terminals using VT escape sequences. This has been incubating in System.CommandLine.Rendering.
