### ISSUE TITLE
Hide subcommand argument

### ISSUE THREAD

**Issue by nxtn** [dotnet/command-line-api#978]
I'm building a CLI similar to `dotnet` where each subcommand has an optional argument. The top level help message looks like the following:

```
Commands:
  install <path-to-config>      ...
  uninstall <path-to-config>    ...
  start <path-to-config>        ...
  stop <path-to-config>         ...
  restart <path-to-config>      ...
  status <path-to-config>       ...
  test <path-to-config>         ...
```

I think this looks a bit messy and confusing - the argument seems to be required (`<>`) rather than optional (`[<>]`). Is it possible to hide the argument here?

**Comment by jonsequitur** [comment]
Would you rather hide it than add the `[` `]` around it to indicate it's optional? Is there a default value?

**Comment by NextTurn** [comment]
I'd prefer to hide it to simplify the top level help message.

There isn't a default value. Its arity is `ZeroOrOne`.

**Comment by StevenRasmussen** [comment]
I'm looking for the ability to also hide both arguments and options from commands (either main or sub commands).  My use case:  I'm building a public CLI that others can use but it will also be used by another application (which I control).  There are certain args/options that I only want this other application to use and know about.  So when an end user queries the help I don't want those args/options to be output to the command line (mostly because it will add noise and confusion as an end user wouldn't know how these args/options are meant to be used).  Thanks

**Comment by StevenRasmussen** [comment]
Also, if this is something where you would consider accepting a PR I'd be happy to try and work this out.  It seems like it could be as simple as adding an `IsHidden` property to an arg and option and then simply check this at the time that the help text is written to the output window.

**Comment by jonsequitur** [comment]
@StevenRasmussen There's an `IsHidden` property on `Symbol` (i.e. `Command`, `Option`, and `Argument`). If you set that, is the help output what you're looking for? What changes would you like to see?

We'd absolutely appreciate a PR as long as we agree on the goal.

**Comment by StevenRasmussen** [comment]
@jonsequitur - Doh!  I totally missed that 🤦‍♂️.  Does exactly what I need! Thanks!

**Comment by nxtn** [comment]
Was this rejected?

**Comment by jonsequitur** [comment]
Nope. We're making the help API more flexible via #1229 which will make this kind of fine-grained customization easier.
